"""
Django settings for contractai project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

# CRITICAL: Import langchain compatibility shim FIRST before any other imports
# This fixes PaddleOCR's dependency on old langchain.docstore module
import sys
sys.path.insert(0, str(__file__).rsplit('\\', 2)[0])  # Add django_backend to path
try:
    import langchain_compat  # noqa: F401
except ImportError:
    pass  # Compatibility module not needed or already loaded

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv

# added by akash
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['72.60.163.124', 'yourdomain.com', 'www.yourdomain.com']

# Update CORS for production
CORS_ALLOWED_ORIGINS = [
    'http://72.60.163.124:3002',
    'https://yourdomain.com',
]
# Disable PaddleX model source connectivity check
os.environ['DISABLE_MODEL_SOURCE_CHECK'] = 'True'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file (use absolute path)
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-b-9fjd*2bsznlv72vbv-t%i+6#o69=wp+_)%)lga0)4bvz3n1b')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

ALLOWED_HOSTS = ['*']  # Or specifically: ['72.60.163.124', 'localhost', '127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'core',
    'api',
    'admin_app',
    'superadmin_app',  # NEW: SuperAdmin user management
    'integrations',    # NEW: Fivetran & Kafka connectors
    'counterfactual',
    'drift',
    'risk',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'contractai.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'contractai.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Using MySQL database
#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.mysql',
#        'NAME': 'contractai_db',
#        'USER': 'root',
#        'PASSWORD': 'Primepanini@2025#',
#        'HOST': '0.0.0.0',
#        'PORT': '3306',
#    }
#}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'contractai_db',
        'USER': 'django_user',      # ❗ NOT root
        'PASSWORD': 'Primepanini@2025$',
        'HOST': '127.0.0.1',        # important
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'core.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}


# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    'http://72.60.163.124:3000',
    'http://72.60.163.124:3001',
    'http://72.60.163.124:3002',  # ADD THIS
    'http://72.60.163.124:3003',
    'http://72.60.163.124:5173',
    'http://localhost:3000',
    'http://localhost:3001',
    'http://localhost:3002',
    'http://localhost:3003',
    'http://localhost:5173',
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = ['*']  # ADD THIS


# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:3001',
    'http://localhost:3002',
    'http://localhost:3003',
    'http://localhost:5173',
    'http://127.0.0.1:3000',
    'http://127.0.0.1:3001',
    'http://127.0.0.1:3002',
    'http://127.0.0.1:5173',
]

CORS_ALLOW_CREDENTIALS = True

# JWT Configuration
JWT_SECRET = os.getenv('JWT_SECRET', 'your-secret-key')
JWT_ALGORITHM = os.getenv('JWT_ALGORITHM', 'HS256')
JWT_EXPIRATION_HOURS = int(os.getenv('JWT_EXPIRATION_HOURS', '24'))

# File Upload Configuration
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')
MEDIA_URL = '/uploads/'
MAX_UPLOAD_SIZE = 25 * 1024 * 1024  # 25MB

# Ensure uploads directory exists
os.makedirs(MEDIA_ROOT, exist_ok=True)

# OCR Configuration
MAX_OCR_PAGES = 30  # Process up to 30 pages with OCR
PDF2PIC_DENSITY = 150

# PaddleOCR Configuration
# PaddleOCR models will auto-download on first use (~150MB)
# Stored in: C:\Users\<username>\.paddleocr\
# No additional system dependencies required!
print('[INFO] Using PaddleOCR for text extraction - models will auto-download on first use') 

# =========================
# ALFRESCO CONFIGURATION
# =========================
#ALFRESCO_URL = os.getenv('ALFRESCO_URL', 'http://localhost:8080/alfresco')
#ALFRESCO_USER = os.getenv('ALFRESCO_USER', 'admin')
#ALFRESCO_PASSWORD = os.getenv('ALFRESCO_PASSWORD', 'admin')

# =========================
# RAG & VECTOR DATABASE CONFIGURATION
# =========================
# ChromaDB Configuration
CHROMADB_PATH = os.path.join(BASE_DIR, 'chroma_db')

# Ensure ChromaDB directory exists
os.makedirs(CHROMADB_PATH, exist_ok=True)

# Contracts-BERT Model (Legal domain embeddings)
# Options:
# - 'nlpaueb/legal-bert-base-uncased' (legal-specific, slower but more accurate)
# - 'sentence-transformers/all-MiniLM-L6-v2' (general purpose, faster)
CONTRACTS_BERT_MODEL = os.getenv('CONTRACTS_BERT_MODEL', 'sentence-transformers/all-MiniLM-L6-v2')

# OpenAI Configuration (Optional - for GPT-4 based extraction)
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', None)

# Ollama Configuration (Default - for local Qwen-based extraction)
OLLAMA_MODEL = os.getenv('OLLAMA_MODEL', 'qwen2.5:0.5b')
OLLAMA_BASE_URL = os.getenv('OLLAMA_BASE_URL', 'http://localhost:11434')

# =========================
# PAYMENT GATEWAY CONFIGURATION
# =========================
# PayPal Configuration
PAYPAL_CLIENT_ID = os.getenv('PAYPAL_CLIENT_ID', 'PAYPAL_CLIENT_ID')
PAYPAL_CLIENT_SECRET = os.getenv('PAYPAL_CLIENT_SECRET', 'PAYPAL_SECRET')
PAYPAL_MODE = os.getenv('PAYPAL_MODE', 'sandbox')  # 'sandbox' or 'live'

# Stripe Configuration
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', 'sk_test_xxxxx')
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY', 'pk_test_xxxxx')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', 'whsec_xxxxx')

# =========================
# EXTERNAL SERVICES CONFIGURATION
# =========================
# Qdrant Vector Database
QDRANT_URL = os.getenv('QDRANT_URL', 'http://localhost:6333')

# Neo4j Graph Database
NEO4J_URI = os.getenv('NEO4J_URI', 'bolt://localhost:7687')
NEO4J_USER = os.getenv('NEO4J_USER', 'neo4j')
NEO4J_PASSWORD = os.getenv('NEO4J_PASSWORD', 'password')

# =========================
# CELERY CONFIGURATION
# =========================
# Redis as message broker and result backend
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')

# Task settings
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes max
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes soft limit

# Task result expiration (24 hours)
CELERY_RESULT_EXPIRES = 60 * 60 * 24

# Worker settings
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000

# =========================
# REDIS CACHE CONFIGURATION
# =========================
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'KEY_PREFIX': 'contractai',
        'TIMEOUT': 300,  # 5 minutes default
    }
}

# =========================
# KAFKA CONFIGURATION
# =========================
# Kafka broker connection
#KAFKA_BOOTSTRAP_SERVERS = os.getenv('KAFKA_BOOTSTRAP_SERVERS', 'localhost:9092')
#KAFKA_CLIENT_ID = os.getenv('KAFKA_CLIENT_ID', 'contractai-django')

# Kafka topics
#KAFKA_TOPICS = {
#    'CONTRACT_INGEST': 'contract.ingest',
#    'CONTRACT_REVIEW_REQUEST': 'contract.review.request',
#    'CONTRACT_RISK_REQUEST': 'contract.risk.request',
#    'CONTRACT_DRIFT_REQUEST': 'contract.drift.request',
#    'CONTRACT_REVIEW_COMPLETED': 'contract.review.completed',
#    'CONTRACT_RISK_SCORED': 'contract.risk.scored',
#    'CONTRACT_DRIFT_DETECTED': 'contract.drift.detected',
#    'CONTRACT_FAILED': 'contract.failed',
#    'FIVETRAN_SYNC': 'integration.fivetran.sync',
#}

