# Generated by Django 4.2.7 on 2026-01-13 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0032_analysisresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClauseRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_risk_score', models.FloatField(db_column='localRiskScore', default=0.0, help_text='Clause-specific risk score (0-1)')),
                ('was_negotiated', models.BooleanField(db_column='wasNegotiated', default=False, help_text='Whether clause was negotiated')),
                ('qdrant_point_id', models.CharField(blank=True, db_column='qdrantPointId', help_text='Point ID in Qdrant vector DB', max_length=100, null=True)),
                ('embedding_synced_at', models.DateTimeField(blank=True, db_column='embeddingSyncedAt', null=True)),
                ('neo4j_relationship_id', models.CharField(blank=True, db_column='neo4jRelationshipId', max_length=100, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, db_column='lastSyncedAt', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'clause_risks',
                'ordering': ['-local_risk_score'],
            },
        ),
        migrations.CreateModel(
            name='ContractRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_risk_score', models.FloatField(db_column='overallRiskScore', default=0.0, help_text='Computed overall risk (0-1)')),
                ('region', models.CharField(blank=True, help_text='Contract region', max_length=100, null=True)),
                ('business_unit', models.CharField(blank=True, db_column='businessUnit', help_text='Business unit owning contract', max_length=100, null=True)),
                ('neo4j_relationship_id', models.CharField(blank=True, db_column='neo4jRelationshipId', max_length=100, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, db_column='lastSyncedAt', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'contract_risks',
                'ordering': ['-overall_risk_score'],
            },
        ),
        migrations.CreateModel(
            name='CrossContractCorrelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_strength', models.FloatField(db_column='correlationStrength', help_text='Strength of correlation (0-1)')),
                ('correlation_reason', models.TextField(db_column='correlationReason', help_text='Why these contracts are correlated')),
                ('same_vendor', models.BooleanField(db_column='sameVendor', default=False)),
                ('same_jurisdiction', models.BooleanField(db_column='sameJurisdiction', default=False)),
                ('similar_clauses', models.BooleanField(db_column='similarClauses', default=False)),
                ('neo4j_relationship_id', models.CharField(blank=True, db_column='neo4jRelationshipId', max_length=100, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_column='detectedAt')),
            ],
            options={
                'db_table': 'cross_contract_correlations',
                'ordering': ['-correlation_strength'],
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Party name (vendor/customer)', max_length=255, unique=True)),
                ('party_type', models.CharField(choices=[('VENDOR', 'Vendor'), ('CUSTOMER', 'Customer'), ('PARTNER', 'Partner')], db_column='partyType', max_length=20)),
                ('country', models.CharField(blank=True, help_text='Country of operation', max_length=100, null=True)),
                ('neo4j_node_id', models.CharField(blank=True, db_column='neo4jNodeId', help_text='Node ID in Neo4j graph', max_length=100, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, db_column='lastSyncedAt', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'parties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VendorExposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_exposure', models.FloatField(db_column='totalExposure', default=0.0, help_text='Total risk exposure from all contracts')),
                ('contract_count', models.IntegerField(db_column='contractCount', default=0, help_text='Number of contracts with this vendor')),
                ('average_risk', models.FloatField(db_column='averageRisk', default=0.0, help_text='Average risk score across contracts')),
                ('exposure_by_region', models.JSONField(db_column='exposureByRegion', default=dict, help_text='{"APAC": 0.82, "EMEA": 0.46, ...}')),
                ('computed_at', models.DateTimeField(auto_now=True, db_column='computedAt', help_text='When exposure was last calculated')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposures', to='risk.party')),
            ],
            options={
                'db_table': 'vendor_exposures',
                'ordering': ['-total_exposure'],
            },
        ),
        migrations.CreateModel(
            name='RiskNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_type', models.CharField(choices=[('LEGAL', 'Legal Risk'), ('FINANCIAL', 'Financial Risk'), ('REGULATORY', 'Regulatory Risk'), ('OPERATIONAL', 'Operational Risk')], db_column='riskType', max_length=20)),
                ('description', models.TextField(help_text='Risk description')),
                ('severity', models.FloatField(default=0.0, help_text='Risk severity score (0-1)')),
                ('neo4j_node_id', models.CharField(blank=True, db_column='neo4jNodeId', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'risk_nodes',
                'ordering': ['-severity', 'risk_type'],
                'indexes': [models.Index(fields=['risk_type'], name='risk_nodes_riskTyp_cfc5bf_idx'), models.Index(fields=['-severity'], name='risk_nodes_severit_b7bec6_idx')],
            },
        ),
        migrations.CreateModel(
            name='PartyPartition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partition_key', models.CharField(db_column='partitionKey', help_text='Partition identifier (e.g., VendorABC_2025)', max_length=100, unique=True)),
                ('year', models.IntegerField(help_text='Year of partition')),
                ('region', models.CharField(blank=True, help_text='Region filter (APAC, EMEA, US)', max_length=100, null=True)),
                ('neo4j_node_id', models.CharField(blank=True, db_column='neo4jNodeId', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partitions', to='risk.party')),
            ],
            options={
                'db_table': 'party_partitions',
                'ordering': ['-year', 'party'],
            },
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['name'], name='parties_name_19bc50_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['party_type'], name='parties_partyTy_6cc42d_idx'),
        ),
        migrations.AddField(
            model_name='crosscontractcorrelation',
            name='contract_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlations_as_a', to='core.contract'),
        ),
        migrations.AddField(
            model_name='crosscontractcorrelation',
            name='contract_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlations_as_b', to='core.contract'),
        ),
        migrations.AddField(
            model_name='contractrisk',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_risks', to='core.contract'),
        ),
        migrations.AddField(
            model_name='contractrisk',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_risks', to='risk.party'),
        ),
        migrations.AddField(
            model_name='clauserisk',
            name='clause',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clause_risk', to='core.clause'),
        ),
        migrations.AddField(
            model_name='clauserisk',
            name='risk_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clause_risks', to='risk.risknode'),
        ),
        migrations.AddIndex(
            model_name='vendorexposure',
            index=models.Index(fields=['party'], name='vendor_expo_party_i_8ed090_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorexposure',
            index=models.Index(fields=['-total_exposure'], name='vendor_expo_totalEx_6c98d7_idx'),
        ),
        migrations.AddIndex(
            model_name='partypartition',
            index=models.Index(fields=['party', 'year'], name='party_parti_party_i_d34f9e_idx'),
        ),
        migrations.AddIndex(
            model_name='partypartition',
            index=models.Index(fields=['partition_key'], name='party_parti_partiti_0432e8_idx'),
        ),
        migrations.AddIndex(
            model_name='crosscontractcorrelation',
            index=models.Index(fields=['contract_a', '-correlation_strength'], name='cross_contr_contrac_a9502a_idx'),
        ),
        migrations.AddIndex(
            model_name='crosscontractcorrelation',
            index=models.Index(fields=['contract_b', '-correlation_strength'], name='cross_contr_contrac_2a70ca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='crosscontractcorrelation',
            unique_together={('contract_a', 'contract_b')},
        ),
        migrations.AddIndex(
            model_name='contractrisk',
            index=models.Index(fields=['contract'], name='contract_ri_contrac_cc00fc_idx'),
        ),
        migrations.AddIndex(
            model_name='contractrisk',
            index=models.Index(fields=['party'], name='contract_ri_party_i_071259_idx'),
        ),
        migrations.AddIndex(
            model_name='contractrisk',
            index=models.Index(fields=['region'], name='contract_ri_region_5a97c6_idx'),
        ),
        migrations.AddIndex(
            model_name='contractrisk',
            index=models.Index(fields=['-overall_risk_score'], name='contract_ri_overall_5bff01_idx'),
        ),
        migrations.AddIndex(
            model_name='clauserisk',
            index=models.Index(fields=['clause'], name='clause_risk_clause__329f28_idx'),
        ),
        migrations.AddIndex(
            model_name='clauserisk',
            index=models.Index(fields=['risk_node'], name='clause_risk_risk_no_9d8063_idx'),
        ),
        migrations.AddIndex(
            model_name='clauserisk',
            index=models.Index(fields=['-local_risk_score'], name='clause_risk_localRi_443e47_idx'),
        ),
    ]
