# Generated by Django 4.2.7 on 2026-01-13 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_analysisresult'),
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clauserisk',
            new_name='clause_risk_clauseI_f3049f_idx',
            old_name='clause_risk_clause__329f28_idx',
        ),
        migrations.RenameIndex(
            model_name='clauserisk',
            new_name='clause_risk_riskNod_40e1b5_idx',
            old_name='clause_risk_risk_no_9d8063_idx',
        ),
        migrations.RenameIndex(
            model_name='contractrisk',
            new_name='contract_ri_contrac_a0c447_idx',
            old_name='contract_ri_contrac_cc00fc_idx',
        ),
        migrations.RenameIndex(
            model_name='contractrisk',
            new_name='contract_ri_partyId_500825_idx',
            old_name='contract_ri_party_i_071259_idx',
        ),
        migrations.RenameIndex(
            model_name='crosscontractcorrelation',
            new_name='cross_contr_contrac_52c020_idx',
            old_name='cross_contr_contrac_a9502a_idx',
        ),
        migrations.RenameIndex(
            model_name='crosscontractcorrelation',
            new_name='cross_contr_contrac_f3c5b1_idx',
            old_name='cross_contr_contrac_2a70ca_idx',
        ),
        migrations.RenameIndex(
            model_name='partypartition',
            new_name='party_parti_partyId_c34584_idx',
            old_name='party_parti_party_i_d34f9e_idx',
        ),
        migrations.RenameIndex(
            model_name='vendorexposure',
            new_name='vendor_expo_partyId_7d0e79_idx',
            old_name='vendor_expo_party_i_8ed090_idx',
        ),
        migrations.AlterField(
            model_name='clauserisk',
            name='clause',
            field=models.OneToOneField(db_column='clauseId', on_delete=django.db.models.deletion.CASCADE, related_name='clause_risk', to='core.clause'),
        ),
        migrations.AlterField(
            model_name='clauserisk',
            name='risk_node',
            field=models.ForeignKey(blank=True, db_column='riskNodeId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clause_risks', to='risk.risknode'),
        ),
        migrations.AlterField(
            model_name='contractrisk',
            name='contract',
            field=models.ForeignKey(db_column='contractId', on_delete=django.db.models.deletion.CASCADE, related_name='contract_risks', to='core.contract'),
        ),
        migrations.AlterField(
            model_name='contractrisk',
            name='party',
            field=models.ForeignKey(blank=True, db_column='partyId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_risks', to='risk.party'),
        ),
        migrations.AlterField(
            model_name='crosscontractcorrelation',
            name='contract_a',
            field=models.ForeignKey(db_column='contractAId', on_delete=django.db.models.deletion.CASCADE, related_name='correlations_as_a', to='core.contract'),
        ),
        migrations.AlterField(
            model_name='crosscontractcorrelation',
            name='contract_b',
            field=models.ForeignKey(db_column='contractBId', on_delete=django.db.models.deletion.CASCADE, related_name='correlations_as_b', to='core.contract'),
        ),
        migrations.AlterField(
            model_name='partypartition',
            name='party',
            field=models.ForeignKey(db_column='partyId', on_delete=django.db.models.deletion.CASCADE, related_name='partitions', to='risk.party'),
        ),
        migrations.AlterField(
            model_name='vendorexposure',
            name='party',
            field=models.ForeignKey(db_column='partyId', on_delete=django.db.models.deletion.CASCADE, related_name='exposures', to='risk.party'),
        ),
    ]
