# Generated by Django 4.2.7 on 2026-01-14 08:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocuSignDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_id', models.CharField(max_length=100)),
                ('document_name', models.CharField(max_length=500)),
                ('document_base64', models.TextField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fivetran_docusign_documents',
            },
        ),
        migrations.CreateModel(
            name='DocuSignEnvelope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('envelope_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('email_subject', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(max_length=50)),
                ('sent_date_time', models.DateTimeField(blank=True, null=True)),
                ('completed_date_time', models.DateTimeField(blank=True, null=True)),
                ('created_date_time', models.DateTimeField(blank=True, null=True)),
                ('sender_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('source_system', models.CharField(default='DOCUSIGN', max_length=50)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('fivetran_synced', models.BooleanField(default=True)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'fivetran_docusign_envelopes',
            },
        ),
        migrations.CreateModel(
            name='DocuSignRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_id', models.CharField(max_length=100)),
                ('role_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fivetran_docusign_recipients',
            },
        ),
        migrations.CreateModel(
            name='SalesforceAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('salesforce_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('account_type', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('billing_street', models.CharField(blank=True, max_length=500, null=True)),
                ('billing_city', models.CharField(blank=True, max_length=200, null=True)),
                ('billing_state', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_country', models.CharField(blank=True, max_length=100, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('fivetran_synced', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'fivetran_salesforce_accounts',
            },
        ),
        migrations.CreateModel(
            name='UnifiedContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('source_system', models.CharField(choices=[('DOCUSIGN', 'DocuSign'), ('SALESFORCE', 'Salesforce'), ('SAP', 'SAP'), ('MANUAL', 'Manual Upload')], max_length=50)),
                ('contract_name', models.CharField(blank=True, max_length=500, null=True)),
                ('contract_number', models.CharField(blank=True, max_length=200, null=True)),
                ('counterparty', models.CharField(max_length=500)),
                ('contract_type', models.CharField(blank=True, max_length=100, null=True)),
                ('contract_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('execution_date', models.DateField(blank=True, null=True)),
                ('lifecycle_status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etl_processed_at', models.DateTimeField(blank=True, null=True)),
                ('qdrant_synced', models.BooleanField(default=False)),
                ('qdrant_synced_at', models.DateTimeField(blank=True, null=True)),
                ('native_contract_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'unified_contracts',
                'indexes': [models.Index(fields=['external_id'], name='unified_con_externa_519d68_idx'), models.Index(fields=['source_system'], name='unified_con_source__d544e7_idx'), models.Index(fields=['counterparty'], name='unified_con_counter_e7bd4c_idx'), models.Index(fields=['qdrant_synced'], name='unified_con_qdrant__4533d0_idx')],
            },
        ),
        migrations.CreateModel(
            name='SapLFA1',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lifnr', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name1', models.CharField(blank=True, max_length=200, null=True)),
                ('land1', models.CharField(blank=True, max_length=10, null=True)),
                ('ort01', models.CharField(blank=True, max_length=200, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('fivetran_synced', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'fivetran_sap_lfa1',
                'indexes': [models.Index(fields=['lifnr'], name='fivetran_sa_lifnr_2d962c_idx')],
            },
        ),
        migrations.CreateModel(
            name='SapEKPO',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ebeln', models.CharField(db_index=True, max_length=20)),
                ('ebelp', models.CharField(max_length=10)),
                ('matnr', models.CharField(blank=True, max_length=40, null=True)),
                ('txz01', models.CharField(blank=True, max_length=500, null=True)),
                ('menge', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('meins', models.CharField(blank=True, max_length=10, null=True)),
                ('netpr', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('netwr', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('fivetran_synced', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'fivetran_sap_ekpo',
                'indexes': [models.Index(fields=['ebeln'], name='fivetran_sa_ebeln_b968d0_idx')],
                'unique_together': {('ebeln', 'ebelp')},
            },
        ),
        migrations.CreateModel(
            name='SapEKKO',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ebeln', models.CharField(db_index=True, max_length=20, unique=True)),
                ('bukrs', models.CharField(blank=True, max_length=10, null=True)),
                ('bsart', models.CharField(blank=True, max_length=10, null=True)),
                ('bstyp', models.CharField(blank=True, max_length=1, null=True)),
                ('lifnr', models.CharField(blank=True, max_length=20, null=True)),
                ('bedat', models.DateField(blank=True, null=True)),
                ('kdatb', models.DateField(blank=True, null=True)),
                ('kdate', models.DateField(blank=True, null=True)),
                ('waers', models.CharField(blank=True, max_length=5, null=True)),
                ('source_system', models.CharField(default='SAP', max_length=50)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('fivetran_synced', models.BooleanField(default=True)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'fivetran_sap_ekko',
                'indexes': [models.Index(fields=['ebeln'], name='fivetran_sa_ebeln_c423f2_idx'), models.Index(fields=['lifnr'], name='fivetran_sa_lifnr_60bb43_idx'), models.Index(fields=['processed'], name='fivetran_sa_process_e695c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='SapCDPOS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('objectid', models.CharField(db_index=True, max_length=100)),
                ('tabname', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('chngind', models.CharField(max_length=1)),
                ('value_old', models.TextField(blank=True, null=True)),
                ('value_new', models.TextField(blank=True, null=True)),
                ('changedby', models.CharField(blank=True, max_length=50, null=True)),
                ('changedat', models.DateField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('fivetran_synced', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'fivetran_sap_cdpos',
                'indexes': [models.Index(fields=['objectid'], name='fivetran_sa_objecti_0ccc6f_idx'), models.Index(fields=['tabname'], name='fivetran_sa_tabname_367ee6_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalesforceOpportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('salesforce_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('stage_name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('probability', models.IntegerField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('fivetran_synced', models.BooleanField(default=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='integrations.salesforceaccount')),
            ],
            options={
                'db_table': 'fivetran_salesforce_opportunities',
            },
        ),
        migrations.CreateModel(
            name='SalesforceContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('salesforce_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('contract_number', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('contract_term', models.IntegerField(blank=True, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source_system', models.CharField(default='SALESFORCE', max_length=50)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('fivetran_synced', models.BooleanField(default=True)),
                ('processed', models.BooleanField(default=False)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='integrations.salesforceaccount')),
            ],
            options={
                'db_table': 'fivetran_salesforce_contracts',
            },
        ),
        migrations.AddIndex(
            model_name='salesforceaccount',
            index=models.Index(fields=['salesforce_id'], name='fivetran_sa_salesfo_df6146_idx'),
        ),
        migrations.AddIndex(
            model_name='salesforceaccount',
            index=models.Index(fields=['name'], name='fivetran_sa_name_68ad25_idx'),
        ),
        migrations.AddField(
            model_name='docusignrecipient',
            name='envelope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='integrations.docusignenvelope'),
        ),
        migrations.AddIndex(
            model_name='docusignenvelope',
            index=models.Index(fields=['envelope_id'], name='fivetran_do_envelop_514d36_idx'),
        ),
        migrations.AddIndex(
            model_name='docusignenvelope',
            index=models.Index(fields=['status'], name='fivetran_do_status_da981a_idx'),
        ),
        migrations.AddIndex(
            model_name='docusignenvelope',
            index=models.Index(fields=['processed'], name='fivetran_do_process_99d377_idx'),
        ),
        migrations.AddField(
            model_name='docusigndocument',
            name='envelope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='integrations.docusignenvelope'),
        ),
        migrations.AddIndex(
            model_name='salesforceopportunity',
            index=models.Index(fields=['salesforce_id'], name='fivetran_sa_salesfo_4a1e5c_idx'),
        ),
        migrations.AddIndex(
            model_name='salesforcecontract',
            index=models.Index(fields=['salesforce_id'], name='fivetran_sa_salesfo_609d1d_idx'),
        ),
        migrations.AddIndex(
            model_name='salesforcecontract',
            index=models.Index(fields=['contract_number'], name='fivetran_sa_contrac_0c49a1_idx'),
        ),
        migrations.AddIndex(
            model_name='salesforcecontract',
            index=models.Index(fields=['processed'], name='fivetran_sa_process_0c0d80_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='docusignrecipient',
            unique_together={('envelope', 'recipient_id')},
        ),
        migrations.AlterUniqueTogether(
            name='docusigndocument',
            unique_together={('envelope', 'document_id')},
        ),
    ]
