# Generated migration for arbitration app

from django.db import migrations, models
import django.db.models.deletion
import core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__latest__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitrationAnalysis',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('totalClauses', models.IntegerField(db_column='totalClauses', default=0)),
                ('highRiskClauses', models.IntegerField(db_column='highRiskClauses', default=0)),
                ('mediumRiskClauses', models.IntegerField(db_column='mediumRiskClauses', default=0)),
                ('lowRiskClauses', models.IntegerField(db_column='lowRiskClauses', default=0)),
                ('avgCompositeRisk', models.FloatField(db_column='avgCompositeRisk', default=0.0, help_text='Average composite risk score 0.0-1.0')),
                ('disputeProbability', models.FloatField(db_column='disputeProbability', default=0.0, help_text='Probability of arbitration dispute')),
                ('overallRiskLevel', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], db_column='overallRiskLevel', default='MEDIUM', max_length=20)),
                ('expectedLoss', models.DecimalField(db_column='expectedLoss', decimal_places=2, default=0, max_digits=18)),
                ('medianLoss', models.DecimalField(db_column='medianLoss', decimal_places=2, default=0, max_digits=18)),
                ('p75Loss', models.DecimalField(db_column='p75Loss', decimal_places=2, default=0, max_digits=18)),
                ('p90Loss', models.DecimalField(db_column='p90Loss', decimal_places=2, default=0, max_digits=18)),
                ('worstCaseP95', models.DecimalField(db_column='worstCaseP95', decimal_places=2, default=0, max_digits=18)),
                ('var99', models.DecimalField(db_column='var99', decimal_places=2, default=0, max_digits=18)),
                ('stdDeviation', models.DecimalField(db_column='stdDeviation', decimal_places=2, default=0, max_digits=18)),
                ('buyerWinProbability', models.FloatField(db_column='buyerWinProbability', default=0.0)),
                ('supplierWinProbability', models.FloatField(db_column='supplierWinProbability', default=0.0)),
                ('partialAwardProbability', models.FloatField(db_column='partialAwardProbability', default=0.0)),
                ('settlementProbability', models.FloatField(db_column='settlementProbability', default=0.0)),
                ('expectedAward', models.DecimalField(db_column='expectedAward', decimal_places=2, default=0, max_digits=18)),
                ('arbitrationExposure', models.DecimalField(db_column='arbitrationExposure', decimal_places=2, default=0, max_digits=18)),
                ('legalCostEstimate', models.DecimalField(db_column='legalCostEstimate', decimal_places=2, default=0, max_digits=18)),
                ('totalExposure', models.DecimalField(db_column='totalExposure', decimal_places=2, default=0, max_digits=18)),
                ('settlementOffer', models.DecimalField(blank=True, db_column='settlementOffer', decimal_places=2, max_digits=18, null=True)),
                ('settlementDecision', models.CharField(blank=True, db_column='settlementDecision', help_text='SETTLE or PROCEED_TO_ARBITRATION', max_length=50, null=True)),
                ('potentialSaving', models.DecimalField(db_column='potentialSaving', decimal_places=2, default=0, max_digits=18)),
                ('optimalSeat', models.CharField(blank=True, db_column='optimalSeat', max_length=50, null=True)),
                ('optimalTribunal', models.CharField(blank=True, db_column='optimalTribunal', max_length=50, null=True)),
                ('optimalCostRule', models.CharField(blank=True, db_column='optimalCostRule', max_length=50, null=True)),
                ('optimalInstitution', models.CharField(blank=True, db_column='optimalInstitution', max_length=50, null=True)),
                ('optimalExpectedCost', models.DecimalField(db_column='optimalExpectedCost', decimal_places=2, default=0, max_digits=18)),
                ('gnnDisputeProbability', models.FloatField(blank=True, db_column='gnnDisputeProbability', help_text='GNN model dispute prediction', null=True)),
                ('gnnConfidence', models.FloatField(blank=True, db_column='gnnConfidence', help_text='GNN prediction confidence', null=True)),
                ('monteCarloRuns', models.IntegerField(db_column='monteCarloRuns', default=50000)),
                ('tribunalRuns', models.IntegerField(db_column='tribunalRuns', default=5000)),
                ('analysisVersion', models.CharField(db_column='analysisVersion', default='1.0', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('contractId', models.ForeignKey(db_column='contractId', help_text='Contract being analyzed', on_delete=django.db.models.deletion.CASCADE, related_name='arbitration_analyses', to='core.contract')),
            ],
            options={
                'db_table': 'arbitration_analyses',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='ArbitrationClause',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('clauseIndex', models.IntegerField(db_column='clauseIndex', help_text='Order in contract')),
                ('clauseText', models.TextField(db_column='clauseText')),
                ('confidence', models.FloatField(default=0.0, help_text='Extraction confidence 0.0-1.0')),
                ('patternHits', models.IntegerField(db_column='patternHits', default=0)),
                ('jurisdictionRisk', models.FloatField(db_column='jurisdictionRisk', default=0.0)),
                ('costExposure', models.FloatField(db_column='costExposure', default=0.0)),
                ('institutionalRisk', models.FloatField(db_column='institutionalRisk', default=0.0)),
                ('tribunalStructure', models.FloatField(db_column='tribunalStructure', default=0.0)),
                ('proceduralRisk', models.FloatField(db_column='proceduralRisk', default=0.0)),
                ('enforcementRisk', models.FloatField(db_column='enforcementRisk', default=0.0)),
                ('delayDisputeRisk', models.FloatField(db_column='delayDisputeRisk', default=0.0)),
                ('subcontractorPassThrough', models.FloatField(db_column='subcontractorPassThrough', default=0.0)),
                ('compositeRisk', models.FloatField(db_column='compositeRisk', default=0.0)),
                ('riskLevel', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], db_column='riskLevel', default='MEDIUM', max_length=20)),
                ('embedding', models.JSONField(blank=True, help_text='LegalBERT embedding vector', null=True)),
                ('graphNodeId', models.CharField(blank=True, db_column='graphNodeId', max_length=50, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('analysisId', models.ForeignKey(db_column='analysisId', on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='arbitration.arbitrationanalysis')),
            ],
            options={
                'db_table': 'arbitration_clauses',
                'ordering': ['analysisId', 'clauseIndex'],
            },
        ),
        migrations.CreateModel(
            name='TribunalSimulation',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('runs', models.IntegerField(default=5000, help_text='Number of Monte Carlo tribunal simulations')),
                ('clauseStrength', models.FloatField(db_column='clauseStrength')),
                ('precedentScore', models.FloatField(db_column='precedentScore')),
                ('jurisdictionScore', models.FloatField(db_column='jurisdictionScore')),
                ('claimStrength', models.FloatField(db_column='claimStrength')),
                ('delayEvidence', models.FloatField(db_column='delayEvidence')),
                ('buyerWinProb', models.FloatField(db_column='buyerWinProb')),
                ('supplierWinProb', models.FloatField(db_column='supplierWinProb')),
                ('partialAwardProb', models.FloatField(db_column='partialAwardProb')),
                ('settlementProb', models.FloatField(db_column='settlementProb')),
                ('expectedAward', models.DecimalField(db_column='expectedAward', decimal_places=2, max_digits=18)),
                ('avgTribunalScore', models.FloatField(db_column='avgTribunalScore')),
                ('scoreStd', models.FloatField(db_column='scoreStd', help_text='Standard deviation of tribunal scores')),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('analysisId', models.ForeignKey(db_column='analysisId', on_delete=django.db.models.deletion.CASCADE, related_name='tribunal_simulations', to='arbitration.arbitrationanalysis')),
            ],
            options={
                'db_table': 'arbitration_tribunal_simulations',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='ArbitrationScenario',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('seat', models.CharField(help_text='Arbitration seat (london, singapore, etc.)', max_length=50)),
                ('tribunalSize', models.CharField(db_column='tribunalSize', help_text='single_arbitrator, three_member, etc.', max_length=50)),
                ('costRule', models.CharField(db_column='costRule', help_text='equal_sharing, loser_pays, etc.', max_length=50)),
                ('institution', models.CharField(help_text='ICC, LCIA, SIAC, etc.', max_length=50)),
                ('expectedCost', models.DecimalField(db_column='expectedCost', decimal_places=2, max_digits=18)),
                ('totalExposure', models.DecimalField(db_column='totalExposure', decimal_places=2, max_digits=18)),
                ('riskIndex', models.FloatField(db_column='riskIndex', help_text='Composite risk multiplier')),
                ('isOptimal', models.BooleanField(db_column='isOptimal', default=False, help_text='Lowest cost configuration')),
                ('isWorst', models.BooleanField(db_column='isWorst', default=False, help_text='Highest cost configuration')),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('analysisId', models.ForeignKey(db_column='analysisId', on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='arbitration.arbitrationanalysis')),
            ],
            options={
                'db_table': 'arbitration_scenarios',
                'ordering': ['expectedCost'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalArbitrationCase',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('caseNumber', models.CharField(db_column='caseNumber', max_length=100, unique=True)),
                ('caseYear', models.IntegerField(db_column='caseYear')),
                ('institution', models.CharField(help_text='ICC, LCIA, SIAC, etc.', max_length=50)),
                ('seat', models.CharField(help_text='Arbitration seat', max_length=100)),
                ('governingLaw', models.CharField(db_column='governingLaw', max_length=100)),
                ('contractType', models.CharField(db_column='contractType', help_text='EPC, service, supply, etc.', max_length=100)),
                ('contractValue', models.DecimalField(db_column='contractValue', decimal_places=2, max_digits=18)),
                ('industrySector', models.CharField(blank=True, db_column='industrySector', max_length=100, null=True)),
                ('numberOfArbitrators', models.IntegerField(db_column='numberOfArbitrators', default=3)),
                ('tribunalComposition', models.CharField(blank=True, db_column='tribunalComposition', max_length=200, null=True)),
                ('hasDelayClaims', models.BooleanField(db_column='hasDelayClaims', default=False)),
                ('hasLiquidatedDamages', models.BooleanField(db_column='hasLiquidatedDamages', default=False)),
                ('hasCostShifting', models.BooleanField(db_column='hasCostShifting', default=False)),
                ('hasSubcontractorDispute', models.BooleanField(db_column='hasSubcontractorDispute', default=False)),
                ('hasMultiParty', models.BooleanField(db_column='hasMultiParty', default=False)),
                ('jurisdictionRiskScore', models.FloatField(blank=True, db_column='jurisdictionRiskScore', null=True)),
                ('enforcementRiskScore', models.FloatField(blank=True, db_column='enforcementRiskScore', null=True)),
                ('proceduralComplexity', models.FloatField(blank=True, db_column='proceduralComplexity', null=True)),
                ('outcome', models.CharField(choices=[('BUYER_WIN', 'Buyer Win'), ('SUPPLIER_WIN', 'Supplier Win'), ('PARTIAL_AWARD', 'Partial Award'), ('SETTLEMENT', 'Settlement'), ('DISMISSED', 'Dismissed')], max_length=20)),
                ('awardAmount', models.DecimalField(blank=True, db_column='awardAmount', decimal_places=2, max_digits=18, null=True)),
                ('awardPercentage', models.FloatField(blank=True, db_column='awardPercentage', help_text='Award as % of claim', null=True)),
                ('arbitrationCost', models.DecimalField(blank=True, db_column='arbitrationCost', decimal_places=2, max_digits=18, null=True)),
                ('durationMonths', models.IntegerField(blank=True, db_column='durationMonths', null=True)),
                ('caseSummary', models.TextField(blank=True, db_column='caseSummary', null=True)),
                ('keyIssues', models.JSONField(blank=True, db_column='keyIssues', help_text='List of key dispute issues', null=True)),
                ('graphFeatures', models.JSONField(blank=True, db_column='graphFeatures', help_text='Graph neural network features', null=True)),
                ('clauseEmbedding', models.JSONField(blank=True, db_column='clauseEmbedding', help_text='Average clause embeddings', null=True)),
                ('usedForTraining', models.BooleanField(db_column='usedForTraining', default=True)),
                ('dataSource', models.CharField(blank=True, db_column='dataSource', max_length=200, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'historical_arbitration_cases',
                'ordering': ['-caseYear', 'caseNumber'],
            },
        ),
        migrations.CreateModel(
            name='ClauseRewrite',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('originalText', models.TextField(db_column='originalText')),
                ('originalRiskScore', models.FloatField(db_column='originalRiskScore')),
                ('rewrittenText', models.TextField(db_column='rewrittenText')),
                ('predictedRiskScore', models.FloatField(db_column='predictedRiskScore', help_text='Expected risk after rewrite')),
                ('riskReduction', models.FloatField(db_column='riskReduction', help_text='Reduction in risk score')),
                ('improvements', models.JSONField(help_text='List of specific improvements made')),
                ('rewriteStrategy', models.CharField(db_column='rewriteStrategy', help_text='buyer_favorable, balanced, supplier_favorable', max_length=100)),
                ('llmModel', models.CharField(db_column='llmModel', default='qwen2.5:0.5b', max_length=100)),
                ('temperature', models.FloatField(default=0.3, help_text='LLM temperature parameter')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('IMPLEMENTED', 'Implemented')], default='DRAFT', max_length=20)),
                ('reviewedBy', models.CharField(blank=True, db_column='reviewedBy', max_length=255, null=True)),
                ('reviewNotes', models.TextField(blank=True, db_column='reviewNotes', null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('clauseId', models.ForeignKey(db_column='clauseId', on_delete=django.db.models.deletion.CASCADE, related_name='rewrites', to='arbitration.arbitrationclause')),
            ],
            options={
                'db_table': 'arbitration_clause_rewrites',
                'ordering': ['-riskReduction', '-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='GNNPrediction',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('modelVersion', models.CharField(db_column='modelVersion', help_text='GNN model version', max_length=50)),
                ('modelCheckpoint', models.CharField(db_column='modelCheckpoint', help_text='Path to model weights', max_length=255)),
                ('disputeProbability', models.FloatField(db_column='disputeProbability')),
                ('buyerWinProbability', models.FloatField(db_column='buyerWinProbability')),
                ('supplierWinProbability', models.FloatField(db_column='supplierWinProbability')),
                ('partialAwardProbability', models.FloatField(db_column='partialAwardProbability')),
                ('settlementProbability', models.FloatField(db_column='settlementProbability')),
                ('predictionConfidence', models.FloatField(db_column='predictionConfidence')),
                ('modelCertainty', models.FloatField(db_column='modelCertainty', help_text='Model confidence score')),
                ('nodeCount', models.IntegerField(db_column='nodeCount')),
                ('edgeCount', models.IntegerField(db_column='edgeCount')),
                ('avgNodeDegree', models.FloatField(db_column='avgNodeDegree')),
                ('graphDensity', models.FloatField(db_column='graphDensity')),
                ('topInfluentialClauses', models.JSONField(db_column='topInfluentialClauses', help_text='Most influential clause IDs')),
                ('attentionWeights', models.JSONField(blank=True, db_column='attentionWeights', help_text='GAT attention weights', null=True)),
                ('inferenceTimeMs', models.FloatField(db_column='inferenceTimeMs', help_text='Prediction latency in milliseconds')),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('analysisId', models.ForeignKey(db_column='analysisId', on_delete=django.db.models.deletion.CASCADE, related_name='gnn_predictions', to='arbitration.arbitrationanalysis')),
            ],
            options={
                'db_table': 'arbitration_gnn_predictions',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.AddIndex(
            model_name='arbitrationanalysis',
            index=models.Index(fields=['contractId', '-createdAt'], name='arbitration_contrac_c3e9be_idx'),
        ),
        migrations.AddIndex(
            model_name='arbitrationanalysis',
            index=models.Index(fields=['overallRiskLevel'], name='arbitration_overall_82f2a6_idx'),
        ),
        migrations.AddIndex(
            model_name='arbitrationanalysis',
            index=models.Index(fields=['disputeProbability'], name='arbitration_dispute_9a7c3f_idx'),
        ),
        migrations.AddIndex(
            model_name='arbitrationclause',
            index=models.Index(fields=['analysisId', 'clauseIndex'], name='arbitration_analysi_2d8e4a_idx'),
        ),
        migrations.AddIndex(
            model_name='arbitrationclause',
            index=models.Index(fields=['riskLevel'], name='arbitration_riskLev_5f3c1b_idx'),
        ),
        migrations.AddIndex(
            model_name='arbitrationclause',
            index=models.Index(fields=['compositeRisk'], name='arbitration_composi_7a2d9e_idx'),
        ),
        migrations.AddIndex(
            model_name='arbitrationscenario',
            index=models.Index(fields=['analysisId', 'expectedCost'], name='arbitration_analysi_1e6f8c_idx'),
        ),
        migrations.AddIndex(
            model_name='arbitrationscenario',
            index=models.Index(fields=['isOptimal'], name='arbitration_isOptim_4b9c2d_idx'),
        ),
        migrations.AddIndex(
            model_name='arbitrationscenario',
            index=models.Index(fields=['isWorst'], name='arbitration_isWorst_3a8e7f_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalarbitrationcase',
            index=models.Index(fields=['institution', 'outcome'], name='historical_institu_5d2f1a_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalarbitrationcase',
            index=models.Index(fields=['caseYear'], name='historical_caseYea_6e4c3b_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalarbitrationcase',
            index=models.Index(fields=['contractType'], name='historical_contrac_8f7d2c_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalarbitrationcase',
            index=models.Index(fields=['usedForTraining'], name='historical_usedFor_9a1e4d_idx'),
        ),
        migrations.AddIndex(
            model_name='clauserewrite',
            index=models.Index(fields=['clauseId', '-createdAt'], name='arbitration_clauseI_2f8e5a_idx'),
        ),
        migrations.AddIndex(
            model_name='clauserewrite',
            index=models.Index(fields=['status'], name='arbitration_status_3b9f6c_idx'),
        ),
        migrations.AddIndex(
            model_name='clauserewrite',
            index=models.Index(fields=['-riskReduction'], name='arbitration_riskRed_4c1a7d_idx'),
        ),
        migrations.AddIndex(
            model_name='gnnprediction',
            index=models.Index(fields=['analysisId', '-createdAt'], name='arbitration_analysi_5d2b8e_idx'),
        ),
        migrations.AddIndex(
            model_name='gnnprediction',
            index=models.Index(fields=['modelVersion'], name='arbitration_modelVe_6e3c9f_idx'),
        ),
    ]
