"""
Django settings for contractai project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

# CRITICAL: Import langchain compatibility shim FIRST before any other imports
# This fixes PaddleOCR's dependency on old langchain.docstore module
import sys
sys.path.insert(0, str(__file__).rsplit('/', 2)[0])  # Add django_backend to path (use '/' for Linux)
try:
    import langchain_compat  # noqa: F401
except ImportError:
    pass  # Compatibility module not needed or already loaded

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv

# Disable PaddleX model source connectivity check
os.environ['DISABLE_MODEL_SOURCE_CHECK'] = 'True'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file (use absolute path)
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-b-9fjd*2bsznlv72vbv-t%i+6#o69=wp+_)%)lga0)4bvz3n1b')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# Allow both localhost and server IP
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '72.60.163.124',
    '*'  # Remove this in production
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',  # Django Channels for WebSocket support
    'rest_framework',
    'corsheaders',
    'core',
    'api',
    'admin_app',
    'superadmin_app',
    'integrations',
    'counterfactual',
    'drift',
    'risk',
    'negotiation',
    'market',
    'contract_twin',
    'radar',
    'llm_engine',
    'embeddings',
    'risk_engine',
    'ingestion',   # Contract Intelligence Ingestion Pipeline
    'autorag',     # AutoRAG — Graph + Vector contract Q&A
    'tenders',     # Tender Intelligence Engine
    'enterprise',  # Enterprise Risk & Profitability Intelligence (CFO Analytics)
    'arbitration', # Arbitration Risk Intelligence Engine (GNN + Neo4j)
    'dispute_predictor', # Dispute Predictor & Simulator (Bayesian + GNN)
    'force_majeure',    # Force Majeure Intelligence Engine (Bayesian + Monte Carlo + War Risk)
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'contractai.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'contractai.wsgi.application'
ASGI_APPLICATION = 'contractai.asgi.application'

# Custom User Model
AUTH_USER_MODEL = 'core.User'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Using MySQL database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'contractai_db'),
        'USER': os.environ.get('DB_USER', 'root'),
        'PASSWORD': os.environ.get('DB_PASSWORD', '1111'),
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        },
    }
}

# Django Channels Configuration
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
        # For production with Redis, use:
        # 'BACKEND': 'channels_redis.core.RedisChannelLayer',
        # 'CONFIG': {
        #     'hosts': [('127.0.0.1', 6379)],
        # },
    },
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =========================
# Arbitration Services Configuration
# =========================
NEO4J_URI = os.getenv('NEO4J_URI', 'bolt://localhost:7687')
NEO4J_USER = os.getenv('NEO4J_USER', 'neo4j')
NEO4J_PASSWORD = os.getenv('NEO4J_PASSWORD', 'password')

OLLAMA_API_URL = os.getenv('OLLAMA_API_URL', 'http://localhost:11434')
OLLAMA_MODEL = os.getenv('OLLAMA_MODEL', 'qwen2.5:7b')

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'core.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# =========================
# CORS Configuration
# =========================
CORS_ALLOWED_ORIGINS = [
    # Production Server
    'http://72.60.163.124',
    'http://72.60.163.124:80',
    'http://72.60.163.124:3000',
    'http://72.60.163.124:3001',
    'http://72.60.163.124:3002',
    'http://72.60.163.124:3003',
    'http://72.60.163.124:5173',
    'http://72.60.163.124:8000',
    'http://72.60.163.124:8002',
    # Local development
    'http://localhost:3000',
    'http://localhost:3001',
    'http://localhost:3002',
    'http://localhost:3003',
    'http://localhost:5173',
    'http://localhost:8000',
    'http://localhost:8002',
    'http://127.0.0.1:3000',
    'http://127.0.0.1:3001',
    'http://127.0.0.1:3002',
    'http://127.0.0.1:5173',
    'http://127.0.0.1:8000',
    'http://127.0.0.1:8002',
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-erp-system',       # Multi-ERP Integration Hub
    'x-api-key',
    'x-correlation-id',
]

# JWT Configuration
JWT_SECRET = os.getenv('JWT_SECRET', 'your-secret-key')
JWT_ALGORITHM = os.getenv('JWT_ALGORITHM', 'HS256')
JWT_EXPIRATION_HOURS = int(os.getenv('JWT_EXPIRATION_HOURS', '720'))  # 30 days

# File Upload Configuration
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')
MEDIA_URL = '/uploads/'
MAX_UPLOAD_SIZE = 25 * 1024 * 1024  # 25MB

# Ensure uploads directory exists
os.makedirs(MEDIA_ROOT, exist_ok=True)

# OCR Configuration
MAX_OCR_PAGES = 30  # Process up to 30 pages with OCR
PDF2PIC_DENSITY = 150

# PaddleOCR Configuration
print('[INFO] Using PaddleOCR for text extraction - models will auto-download on first use')

# =========================
# ALFRESCO CONFIGURATION
# =========================
ALFRESCO_URL = os.getenv('ALFRESCO_URL', 'http://localhost:8080/alfresco')
ALFRESCO_USER = os.getenv('ALFRESCO_USER', 'admin')
ALFRESCO_PASSWORD = os.getenv('ALFRESCO_PASSWORD', 'admin')

# =========================
# RAG & VECTOR DATABASE CONFIGURATION
# =========================
# ChromaDB Configuration
CHROMADB_PATH = os.path.join(BASE_DIR, 'chroma_db')

# Ensure ChromaDB directory exists
os.makedirs(CHROMADB_PATH, exist_ok=True)

CONTRACTS_BERT_MODEL = os.getenv('CONTRACTS_BERT_MODEL', 'sentence-transformers/all-MiniLM-L6-v2')

# ---------------------------------------------------------------------------
# Embedding model selector – opt-in toggle (SuperAdmin UI)
# Supported keys must match EMBEDDING_MODEL_OPTIONS below exactly.
# ---------------------------------------------------------------------------
EMBEDDING_MODEL_OPTIONS = {
    'minilm': {
        'model_id': 'sentence-transformers/all-MiniLM-L6-v2',
        'label': 'MiniLM-L6-v2',
        'description': 'Lightweight sentence-transformer (384-dim). Fast, low memory.',
        'dimensions': 384,
        'loader': 'sentence_transformers',   # uses SentenceTransformer
    },
    'bert-large-uncased': {
        'model_id': 'bert-large-uncased',
        'label': 'BERT Large (uncased)',
        'description': 'Google BERT-large pretrained on English (1024-dim). Heavier, richer context.',
        'dimensions': 1024,
        'loader': 'transformers',            # uses BertModel + BertTokenizer
    },
}

# Which model is active right now (persisted at runtime via the singleton; default from env)
EMBEDDING_MODEL_KEY = os.getenv('EMBEDDING_MODEL_KEY', 'minilm')

# OpenAI Configuration (Optional - for GPT-4 based extraction)
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', None)

# Ollama Configuration (Default - for local Qwen-based extraction)
OLLAMA_MODEL = os.getenv('OLLAMA_MODEL', 'qwen2.5:7b')
OLLAMA_BASE_URL = os.getenv('OLLAMA_BASE_URL', 'http://localhost:11434')

# Force Majeure Live Data APIs
NEWS_API_KEY = os.getenv('NEWS_API_KEY', '')  # Free tier: https://newsapi.org/register

# =========================
# PAYMENT GATEWAY CONFIGURATION
# =========================
PAYPAL_CLIENT_ID = os.getenv('PAYPAL_CLIENT_ID', 'PAYPAL_CLIENT_ID')
PAYPAL_CLIENT_SECRET = os.getenv('PAYPAL_CLIENT_SECRET', 'PAYPAL_SECRET')
PAYPAL_MODE = os.getenv('PAYPAL_MODE', 'sandbox')

STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', 'sk_test_xxxxx')
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY', 'pk_test_xxxxx')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', 'whsec_xxxxx')

# =========================
# EXTERNAL SERVICES CONFIGURATION
# =========================
_qdrant_host = os.getenv('QDRANT_HOST', 'localhost')
_qdrant_port = os.getenv('QDRANT_PORT', '6333')
QDRANT_URL = os.getenv('QDRANT_URL', f'http://{_qdrant_host}:{_qdrant_port}')

NEO4J_URI = os.getenv('NEO4J_URI', 'bolt://localhost:7687')
NEO4J_USER = os.getenv('NEO4J_USER', 'neo4j')
NEO4J_PASSWORD = os.getenv('NEO4J_PASSWORD', 'password')

# =========================
# CELERY CONFIGURATION
# =========================
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60
CELERY_RESULT_EXPIRES = 60 * 60 * 24
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000

# =========================
# REDIS CACHE CONFIGURATION
# =========================
# Try Redis first, fallback to in-memory cache if Redis is not available
import socket

def is_redis_available():
    try:
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.settimeout(1)
        import urllib.parse
        redis_url = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/0')
        parsed = urllib.parse.urlparse(redis_url)
        host = parsed.hostname or '127.0.0.1'
        port = parsed.port or 6379
        result = sock.connect_ex((host, port))
        sock.close()
        return result == 0
    except:
        return False

if is_redis_available():
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1'),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
            'KEY_PREFIX': 'contractai',
            'TIMEOUT': 300,
        }
    }
    print('[INFO] Using Redis cache')
else:
    # Fallback to in-memory cache when Redis is not available
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'contractai-cache',
            'OPTIONS': {
                'MAX_ENTRIES': 1000
            }
        }
    }
    print('[WARNING] Redis not available, using in-memory cache')

# =========================
# KAFKA CONFIGURATION
# =========================
KAFKA_BOOTSTRAP_SERVERS = os.getenv('KAFKA_BOOTSTRAP_SERVERS', 'localhost:9092')
KAFKA_BROKER_URL = os.getenv('KAFKA_BROKER_URL', 'localhost:9092')
KAFKA_CLIENT_ID = os.getenv('KAFKA_CLIENT_ID', 'contractai-django')
KAFKA_ENABLED = os.getenv('KAFKA_ENABLED', 'true').lower() == 'true'  # Docker Kafka running on port 9092

KAFKA_TOPICS = {
    'CONTRACT_INGEST': 'contract.ingest',
    'CONTRACT_REVIEW_REQUEST': 'contract.review.request',
    'CONTRACT_RISK_REQUEST': 'contract.risk.request',
    'CONTRACT_DRIFT_REQUEST': 'contract.drift.request',
    'CONTRACT_REVIEW_COMPLETED': 'contract.review.completed',
    'CONTRACT_RISK_SCORED': 'contract.risk.scored',
    'CONTRACT_DRIFT_DETECTED': 'contract.drift.detected',
    'CONTRACT_FAILED': 'contract.failed',
    'FIVETRAN_SYNC': 'integration.fivetran.sync',
    'LEGAL_EVENTS': 'legal_events',
}


