# Generated by Django 4.2.7 on 2026-01-12 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractDrift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(db_index=True, max_length=64)),
                ('drift_type', models.CharField(db_index=True, help_text='Type of drift: scope_creep, implied_amendment, waiver, etc.', max_length=64)),
                ('contract_terms', models.TextField(help_text='Original contract terms')),
                ('detected_behavior', models.TextField(help_text='Observed behavior that deviates from contract')),
                ('behavior_context', models.JSONField(blank=True, help_text='Additional context from CRM, support tickets, emails, etc.', null=True)),
                ('legal_risk', models.TextField(help_text='Detailed legal risk analysis')),
                ('business_impact', models.TextField(blank=True, help_text='Impact on revenue, obligations, precedent', null=True)),
                ('severity', models.IntegerField(default=5, help_text='Severity rating from 1 (low) to 10 (critical)')),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('acknowledged', 'Acknowledged'), ('remediation_planned', 'Remediation Planned'), ('remediation_in_progress', 'Remediation In Progress'), ('resolved', 'Resolved'), ('accepted', 'Accepted as New Norm')], db_index=True, default='detected', max_length=32)),
                ('legal_doctrines', models.JSONField(default=list, help_text='List of legal doctrines: waiver, estoppel, course of dealing, etc.')),
                ('remediation_recommendations', models.TextField(blank=True, help_text='Recommended actions to address the drift', null=True)),
                ('remediation_taken', models.TextField(blank=True, help_text='Actions actually taken to remediate', null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drift_duration_days', models.IntegerField(blank=True, help_text='How long the drift has been occurring', null=True)),
                ('frequency_count', models.IntegerField(default=1, help_text='Number of times this drift pattern has occurred')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_drifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contract_drift',
                'ordering': ['-severity', '-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='BehaviorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(db_index=True, max_length=64)),
                ('data_source', models.CharField(choices=[('crm', 'CRM System'), ('billing', 'Billing System'), ('support', 'Support Tickets'), ('email', 'Email Communications'), ('slack', 'Slack Messages'), ('manual', 'Manual Entry')], max_length=64)),
                ('behavior_description', models.TextField()),
                ('behavior_date', models.DateField()),
                ('related_user_id', models.CharField(blank=True, max_length=128, null=True)),
                ('related_ticket_id', models.CharField(blank=True, max_length=128, null=True)),
                ('raw_data', models.JSONField(blank=True, help_text='Raw data from the source system', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_logs', to='drift.contractdrift')),
            ],
            options={
                'db_table': 'behavior_logs',
                'ordering': ['-behavior_date'],
            },
        ),
        migrations.CreateModel(
            name='DriftAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('critical_severity', 'Critical Severity'), ('legal_risk', 'Legal Risk'), ('revenue_impact', 'Revenue Impact'), ('compliance_issue', 'Compliance Issue')], max_length=32)),
                ('alert_message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('drift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='drift.contractdrift')),
            ],
            options={
                'db_table': 'drift_alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['drift', 'is_read'], name='drift_alert_drift_i_7e2a93_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='contractdrift',
            index=models.Index(fields=['contract_id', '-detected_at'], name='contract_dr_contrac_989eae_idx'),
        ),
        migrations.AddIndex(
            model_name='contractdrift',
            index=models.Index(fields=['user', 'status', '-detected_at'], name='contract_dr_user_id_e9cf3b_idx'),
        ),
        migrations.AddIndex(
            model_name='contractdrift',
            index=models.Index(fields=['severity', 'status'], name='contract_dr_severit_bbabc3_idx'),
        ),
        migrations.AddIndex(
            model_name='contractdrift',
            index=models.Index(fields=['drift_type'], name='contract_dr_drift_t_9af455_idx'),
        ),
        migrations.AddIndex(
            model_name='behaviorlog',
            index=models.Index(fields=['contract_id', '-behavior_date'], name='behavior_lo_contrac_4c9448_idx'),
        ),
        migrations.AddIndex(
            model_name='behaviorlog',
            index=models.Index(fields=['data_source', '-behavior_date'], name='behavior_lo_data_so_64ad3c_idx'),
        ),
    ]
