# Generated by Django 4.2.7 on 2026-01-12 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_analysisresult'),
        ('drift', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractdrift',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_drifts', to='core.user'),
        ),
    ]
