# Generated by Django 4.2.7 on 2026-01-12 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('contract_type', models.CharField(max_length=128)),
                ('industry', models.CharField(blank=True, max_length=128, null=True)),
                ('contract_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('dispute_occurred', models.BooleanField(default=False)),
                ('dispute_details', models.TextField(blank=True, null=True)),
                ('revenue_impact', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('litigation_occurred', models.BooleanField(default=False)),
                ('renewal_success', models.BooleanField(blank=True, null=True)),
                ('operational_delays_days', models.IntegerField(blank=True, null=True)),
                ('key_clauses', models.JSONField(help_text='Structured representation of key contract clauses')),
                ('embedding_id', models.CharField(blank=True, help_text='Reference to vector embedding in Qdrant', max_length=128, null=True)),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('outcome_recorded_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'historical_outcomes',
                'ordering': ['-outcome_recorded_date'],
                'indexes': [models.Index(fields=['contract_type', 'industry'], name='historical__contrac_fc9603_idx'), models.Index(fields=['dispute_occurred', 'litigation_occurred'], name='historical__dispute_f811e7_idx')],
            },
        ),
        migrations.CreateModel(
            name='CounterfactualScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(db_index=True, max_length=64)),
                ('original_clause', models.TextField(help_text='Original contract clause')),
                ('modified_clause', models.TextField(help_text='Modified/counterfactual clause')),
                ('simulated_outcome', models.JSONField(help_text='Predicted outcomes including business, legal, and operational impacts')),
                ('confidence_score', models.FloatField(help_text='Confidence level of the simulation (0.0 to 1.0)')),
                ('risk_delta', models.FloatField(blank=True, help_text='Change in risk level compared to original (-1.0 to 1.0)', null=True)),
                ('business_impact', models.JSONField(blank=True, help_text='Revenue, pricing, and financial impacts', null=True)),
                ('legal_impact', models.JSONField(blank=True, help_text='Litigation, compliance, and regulatory impacts', null=True)),
                ('operational_impact', models.JSONField(blank=True, help_text='Delays, resource allocation, and process impacts', null=True)),
                ('scenario_type', models.CharField(default='clause_modification', help_text='Type of counterfactual scenario', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterfactual_scenarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'counterfactual_scenarios',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['contract_id', '-created_at'], name='counterfact_contrac_fdb6e5_idx'), models.Index(fields=['user', '-created_at'], name='counterfact_user_id_967f52_idx')],
            },
        ),
    ]
