# Generated by Django 4.2.7 on 2026-01-27 09:17

from django.db import migrations, models
import django.db.models.deletion
import negotiation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0038_alter_clausedeviationscore_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClauseInteractionPattern',
            fields=[
                ('id', models.CharField(default=negotiation.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('clause_types', models.JSONField(db_column='clauseTypes', help_text='Array of clause types that interact [clauseA, clauseB]')),
                ('risk_type', models.CharField(db_column='riskType', help_text='Type of risk this pattern creates', max_length=100)),
                ('pattern_description', models.TextField(db_column='patternDescription', help_text='Description of the dangerous pattern')),
                ('impact_multiplier', models.FloatField(db_column='impactMultiplier', default=0.3, help_text='Multiplier for financial impact calculation')),
                ('vector_embedding', models.JSONField(blank=True, db_column='vectorEmbedding', help_text='Embedding vector for similarity search', null=True)),
                ('is_active', models.BooleanField(db_column='isActive', default=True, help_text='Whether this pattern is actively used for detection')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
            ],
            options={
                'db_table': 'clause_interaction_patterns',
                'ordering': ['-impact_multiplier'],
            },
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.CharField(default=negotiation.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('risk_profile', models.FloatField(default=0.5, help_text='Overall risk profile score (0=low, 1=high)')),
                ('aggressiveness_score', models.FloatField(default=0.5, help_text='How aggressive in negotiations (0=flexible, 1=aggressive)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'verbose_name_plural': 'counterparties',
                'db_table': 'counterparties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContractNegotiation',
            fields=[
                ('id', models.CharField(default=negotiation.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('contract_name', models.CharField(db_column='contractName', help_text='Name or reference of the contract', max_length=255)),
                ('status', models.CharField(choices=[('SIMULATED', 'Simulated'), ('IN_PROGRESS', 'In Progress'), ('SIGNED', 'Signed'), ('STALLED', 'Stalled'), ('ABANDONED', 'Abandoned')], default='SIMULATED', max_length=50)),
                ('total_rounds', models.IntegerField(db_column='totalRounds', default=0, help_text='Total number of negotiation rounds')),
                ('stall_probability', models.FloatField(db_column='stallProbability', default=0.0, help_text='Overall probability of negotiation stalling')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('contract', models.ForeignKey(blank=True, db_column='contractId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='core.contract')),
                ('counterparty', models.ForeignKey(db_column='counterpartyId', on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='negotiation.counterparty')),
            ],
            options={
                'db_table': 'contract_negotiations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SilentRisk',
            fields=[
                ('id', models.CharField(default=negotiation.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('risk_type', models.CharField(choices=[('CROSS_CLAUSE_CONFLICT', 'Cross-Clause Conflict'), ('LATENT_FINANCIAL_TRIGGER', 'Latent Financial Trigger'), ('DELAYED_LIABILITY', 'Delayed Liability Explosion'), ('HIDDEN_COST_ESCALATION', 'Hidden Cost Escalation'), ('NON_RECOVERABLE_SPEND', 'Non-Recoverable Spend'), ('LONG_TAIL_LIABILITY', 'Long-Tail Liability'), ('TERMINATION_PAYMENT_MISMATCH', 'Termination-Payment Mismatch')], db_column='riskType', help_text='Type of emergent risk', max_length=100)),
                ('description', models.TextField(help_text='Human-readable description of the risk')),
                ('clause_pair', models.JSONField(db_column='clausePair', default=list, help_text='Array of clause types involved [clauseA, clauseB]')),
                ('financial_exposure', models.FloatField(db_column='financialExposure', help_text='Estimated financial exposure in contract currency')),
                ('confidence', models.FloatField(default=0.0, help_text='Confidence score of the detection (0-1)')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_column='detectedAt')),
                ('contract', models.ForeignKey(db_column='contractId', on_delete=django.db.models.deletion.CASCADE, related_name='silent_risks', to='core.contract')),
            ],
            options={
                'db_table': 'silent_risks',
                'ordering': ['-severity', '-financial_exposure'],
                'indexes': [models.Index(fields=['contract', 'risk_type'], name='silent_risk_contrac_3147a1_idx'), models.Index(fields=['severity'], name='silent_risk_severit_7f13c6_idx'), models.Index(fields=['confidence'], name='silent_risk_confide_c1240e_idx')],
            },
        ),
        migrations.CreateModel(
            name='NegotiationPrediction',
            fields=[
                ('id', models.CharField(default=negotiation.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('clause_type', models.CharField(db_column='clauseType', max_length=100)),
                ('clause_text', models.TextField(db_column='clauseText')),
                ('acceptance_probability', models.FloatField(db_column='acceptanceProbability')),
                ('expected_redlines', models.IntegerField(db_column='expectedRedlines')),
                ('stall_risk', models.FloatField(db_column='stallRisk')),
                ('actual_accepted', models.BooleanField(blank=True, db_column='actualAccepted', help_text='Actual outcome (for validation)', null=True)),
                ('actual_redlines', models.IntegerField(blank=True, db_column='actualRedlines', help_text='Actual redline rounds', null=True)),
                ('prediction_date', models.DateTimeField(auto_now_add=True, db_column='predictionDate')),
                ('contract', models.ForeignKey(blank=True, db_column='contractId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='negotiation_predictions', to='core.contract')),
                ('counterparty', models.ForeignKey(db_column='counterpartyId', on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='negotiation.counterparty')),
            ],
            options={
                'db_table': 'negotiation_predictions',
                'ordering': ['-prediction_date'],
                'indexes': [models.Index(fields=['counterparty', 'clause_type'], name='negotiation_counter_70f8d6_idx'), models.Index(fields=['prediction_date'], name='negotiation_predict_779fa7_idx')],
            },
        ),
        migrations.CreateModel(
            name='NegotiationHistory',
            fields=[
                ('id', models.CharField(default=negotiation.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('clause_type', models.CharField(db_column='clauseType', help_text='Type of clause (e.g., IP Ownership, Termination)', max_length=100)),
                ('clause_text', models.TextField(db_column='clauseText', help_text='Original clause text')),
                ('deviation_score', models.FloatField(db_column='deviationScore', default=0.0, help_text='How much it deviates from standard (0-1)')),
                ('accepted', models.BooleanField(default=False, help_text='Whether the clause was accepted without major changes')),
                ('redline_rounds', models.IntegerField(db_column='redlineRounds', default=0, help_text='Number of negotiation rounds')),
                ('stalled', models.BooleanField(default=False, help_text='Whether negotiation stalled on this clause')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('counterparty', models.ForeignKey(db_column='counterpartyId', on_delete=django.db.models.deletion.CASCADE, related_name='negotiation_history', to='negotiation.counterparty')),
            ],
            options={
                'db_table': 'negotiation_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['counterparty', 'clause_type'], name='negotiation_counter_145142_idx'), models.Index(fields=['accepted'], name='negotiation_accepte_8928f8_idx'), models.Index(fields=['stalled'], name='negotiation_stalled_979364_idx')],
            },
        ),
        migrations.CreateModel(
            name='NegotiationClauseState',
            fields=[
                ('id', models.CharField(default=negotiation.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('clause_type', models.CharField(db_column='clauseType', help_text='Type of clause', max_length=100)),
                ('proposed_text', models.TextField(db_column='proposedText', help_text='Proposed clause text')),
                ('accepted', models.BooleanField(default=False, help_text='Whether this clause has been accepted')),
                ('round_number', models.IntegerField(db_column='roundNumber', default=0, help_text='Negotiation round when this state was recorded')),
                ('acceptance_probability', models.FloatField(db_column='acceptanceProbability', default=0.0, help_text='Predicted probability of acceptance')),
                ('stall_risk', models.FloatField(db_column='stallRisk', default=0.0, help_text='Risk of negotiation stalling on this clause')),
                ('expected_redlines', models.IntegerField(db_column='expectedRedlines', default=0, help_text='Expected number of redline rounds')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('negotiation', models.ForeignKey(db_column='negotiationId', on_delete=django.db.models.deletion.CASCADE, related_name='clause_states', to='negotiation.contractnegotiation')),
            ],
            options={
                'db_table': 'negotiation_clause_states',
                'ordering': ['round_number', 'clause_type'],
                'indexes': [models.Index(fields=['negotiation', 'round_number'], name='negotiation_negotia_ad86cc_idx'), models.Index(fields=['accepted'], name='negotiation_accepte_eb30c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='CounterpartyBehaviorSnapshot',
            fields=[
                ('id', models.CharField(default=negotiation.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('avg_acceptance_rate', models.FloatField(db_column='avgAcceptanceRate', help_text='Average clause acceptance rate')),
                ('avg_redline_rounds', models.FloatField(db_column='avgRedlineRounds', help_text='Average number of redline rounds')),
                ('stall_rate', models.FloatField(db_column='stallRate', help_text='Percentage of clauses that stalled')),
                ('aggressiveness_score', models.FloatField(db_column='aggressivenessScore', help_text='Calculated aggressiveness (1 - acceptance_rate)')),
                ('elasticity_score', models.FloatField(db_column='elasticityScore', help_text='Flexibility after redlines (acceptance / redlines)')),
                ('snapshot_date', models.DateField(auto_now_add=True, db_column='snapshotDate')),
                ('counterparty', models.ForeignKey(db_column='counterpartyId', on_delete=django.db.models.deletion.CASCADE, related_name='behavior_snapshots', to='negotiation.counterparty')),
            ],
            options={
                'db_table': 'counterparty_behavior_snapshots',
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['counterparty', 'snapshot_date'], name='counterpart_counter_529e4c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='contractnegotiation',
            index=models.Index(fields=['counterparty', 'status'], name='contract_ne_counter_f7ed28_idx'),
        ),
        migrations.AddIndex(
            model_name='contractnegotiation',
            index=models.Index(fields=['status'], name='contract_ne_status_16e5b9_idx'),
        ),
    ]
