"""
Clause Suggestion Engine for Infor ERP contracts.
"""
from typing import Dict, Any, List


class InforClauseEngine:

    def suggest(self, contract: Dict[str, Any], risk_score: int) -> List[str]:
        suggestions = []
        desc = (contract.get("description") or "").upper()
        net_amount = float(contract.get("netAmount") or 0)

        if risk_score > 70:
            suggestions.append("Insert liability cap clause (recommend capping at contract value)")
            suggestions.append("Add mandatory arbitration clause for dispute resolution")
            suggestions.append("Include performance milestone checkpoints with review gates")

        if "INDEMNITY" in desc:
            suggestions.append("Limit indemnity scope to direct damages only")
            suggestions.append("Add mutual indemnity clause to balance obligations")

        if net_amount > 1_000_000:
            suggestions.append("Include escrow or performance bond for contracts exceeding $1M")

        if "TERMINATION" in desc:
            suggestions.append("Add termination for convenience with 90-day notice period")

        if "EXCLUSIV" in desc:
            suggestions.append("Limit exclusivity to specific geography or product category")

        if not suggestions:
            suggestions.append("Contract appears within standard risk parameters")

        return suggestions

    def generate_note(self, contract: Dict[str, Any], suggestions: List[str]) -> str:
        contract_id = contract.get("contractId") or contract.get("id") or "N/A"
        vendor = contract.get("vendorName") or "N/A"
        amount = float(contract.get("netAmount") or 0)

        lines = [
            "=== PrimeContractAI — Clause Improvement Suggestions ===",
            f"Contract: {contract_id}",
            f"Vendor: {vendor}",
            f"Value: ${amount:,.2f}",
            "",
            "Suggested Improvements:",
        ]
        for i, s in enumerate(suggestions, 1):
            lines.append(f"  {i}. {s}")

        lines += [
            "",
            "Generated by: PrimeContractAI Decision Intelligence Engine",
        ]
        return "\n".join(lines)
