# Generated by Django 4.2.7 on 2025-12-03 14:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('Admin', 'Admin'), ('Legal Reviewer', 'Legal Reviewer'), ('Proc Reviewer', 'Proc Reviewer'), ('Viewer', 'Viewer')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.role')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('file_path', models.TextField()),
                ('full_text', models.TextField(blank=True, null=True)),
                ('contract_type', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('ocr_performed', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.user')),
            ],
            options={
                'db_table': 'contracts',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clause_name', models.CharField(max_length=150)),
                ('found', models.BooleanField(default=False)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('match_count', models.IntegerField(blank=True, null=True)),
                ('text_spans', models.TextField(blank=True, null=True)),
                ('context_sentences', models.TextField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='core.contract')),
            ],
            options={
                'db_table': 'clauses',
                'ordering': ['-confidence'],
            },
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['user', '-uploaded_at'], name='contracts_user_id_6ee1a8_idx'),
        ),
        migrations.AddIndex(
            model_name='clause',
            index=models.Index(fields=['contract', 'clause_name'], name='clauses_contrac_a6716e_idx'),
        ),
        migrations.AddIndex(
            model_name='clause',
            index=models.Index(fields=['contract'], name='clauses_contrac_12f072_idx'),
        ),
    ]
