# Generated by Django 4.2.7 on 2025-12-10 08:55

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_executive_summary'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clause',
            new_name='clauses_contrac_568735_idx',
            old_name='clauses_contrac_a6716e_idx',
        ),
        migrations.RenameIndex(
            model_name='clause',
            new_name='clauses_contrac_af8837_idx',
            old_name='clauses_contrac_12f072_idx',
        ),
        migrations.RenameIndex(
            model_name='contract',
            new_name='contracts_userId_f200f7_idx',
            old_name='contracts_user_id_6ee1a8_idx',
        ),
        migrations.AlterField(
            model_name='clause',
            name='clause_name',
            field=models.CharField(db_column='clauseName', max_length=150),
        ),
        migrations.AlterField(
            model_name='clause',
            name='context_sentences',
            field=models.TextField(blank=True, db_column='contextSentences', null=True),
        ),
        migrations.AlterField(
            model_name='clause',
            name='contract',
            field=models.ForeignKey(db_column='contractId', on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='core.contract'),
        ),
        migrations.AlterField(
            model_name='clause',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt'),
        ),
        migrations.AlterField(
            model_name='clause',
            name='extracted_text',
            field=models.TextField(blank=True, db_column='extractedText', null=True),
        ),
        migrations.AlterField(
            model_name='clause',
            name='id',
            field=models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clause',
            name='match_count',
            field=models.IntegerField(blank=True, db_column='matchCount', null=True),
        ),
        migrations.AlterField(
            model_name='clause',
            name='text_spans',
            field=models.TextField(blank=True, db_column='textSpans', null=True),
        ),
        migrations.AlterField(
            model_name='clause',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='confidence_score',
            field=models.FloatField(blank=True, db_column='confidenceScore', null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(blank=True, db_column='contractType', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='file_path',
            field=models.TextField(db_column='filePath'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='file_type',
            field=models.CharField(db_column='fileType', max_length=50),
        ),
        migrations.AlterField(
            model_name='contract',
            name='full_text',
            field=models.TextField(blank=True, db_column='fullText', null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='id',
            field=models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contract',
            name='ocr_performed',
            field=models.BooleanField(db_column='ocrPerformed', default=False),
        ),
        migrations.AlterField(
            model_name='contract',
            name='original_filename',
            field=models.CharField(db_column='originalFilename', max_length=255),
        ),
        migrations.AlterField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_column='uploadedAt'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='user',
            field=models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.user'),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt'),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, db_column='firstName', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_column='isActive', default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, db_column='lastLogin', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, db_column='lastName', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(db_column='roleId', on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt'),
        ),
    ]
