# Generated by Django 4.2.7 on 2025-12-10 14:45

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_clauses_contrac_a6716e_idx_clauses_contrac_568735_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractObligation',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('full_text', models.TextField(blank=True, db_column='fullText', null=True)),
                ('category', models.CharField(choices=[('PAYMENT', 'Payment'), ('DELIVERY', 'Delivery'), ('COMPLIANCE', 'Compliance'), ('REPORTING', 'Reporting'), ('NOTICE', 'Notice'), ('TERMINATION', 'Termination'), ('OTHER', 'Other')], max_length=50)),
                ('responsible_party', models.CharField(choices=[('YOUR_COMPANY', 'Your Company'), ('COUNTERPARTY', 'Counterparty'), ('BOTH', 'Both Parties')], db_column='responsibleParty', max_length=50)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=20)),
                ('due_date_text', models.CharField(blank=True, db_column='dueDateText', max_length=200, null=True)),
                ('clause_reference', models.CharField(blank=True, db_column='clauseReference', max_length=200, null=True)),
                ('is_completed', models.BooleanField(db_column='isCompleted', default=False)),
                ('completed_at', models.DateTimeField(blank=True, db_column='completedAt', null=True)),
                ('completion_notes', models.TextField(blank=True, db_column='completionNotes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('contract', models.ForeignKey(db_column='contractId', on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='core.contract', to_field='id')),
            ],
            options={
                'db_table': 'contract_obligations',
                'ordering': ['-priority', 'responsible_party', 'category'],
            },
        ),
    ]
