# Generated by Django 4.2.7 on 2025-12-11 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contractobligation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_duration',
            field=models.CharField(blank=True, db_column='contractDuration', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_value',
            field=models.CharField(blank=True, db_column='contractValue', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='party_name',
            field=models.CharField(blank=True, db_column='partyName', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contractobligation',
            name='contract',
            field=models.ForeignKey(db_column='contractId', on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='core.contract'),
        ),
        migrations.AlterField(
            model_name='contractobligation',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, db_column='updatedAt'),
        ),
    ]
