# Generated by Django 4.2.7 on 2025-12-12 10:31

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contractversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractVersion',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField(db_column='versionNumber')),
                ('change_description', models.TextField(blank=True, db_column='changeDescription', null=True)),
                ('filename', models.CharField(max_length=255)),
                ('original_filename', models.CharField(db_column='originalFilename', max_length=255)),
                ('file_type', models.CharField(db_column='fileType', max_length=50)),
                ('file_path', models.TextField(db_column='filePath')),
                ('full_text', models.TextField(blank=True, db_column='fullText', null=True)),
                ('contract_type', models.CharField(blank=True, db_column='contractType', max_length=100, null=True)),
                ('contract_value', models.CharField(blank=True, db_column='contractValue', max_length=100, null=True)),
                ('party_name', models.CharField(blank=True, db_column='partyName', max_length=255, null=True)),
                ('contract_duration', models.CharField(blank=True, db_column='contractDuration', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('contract', models.ForeignKey(db_column='contractId', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.contract')),
                ('created_by', models.ForeignKey(db_column='createdBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_versions', to='core.user')),
            ],
            options={
                'db_table': 'contract_versions',
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['contract', '-version_number'], name='contract_ve_contrac_7e89ff_idx')],
                'unique_together': {('contract', 'version_number')},
            },
        ),
    ]
