# Generated by Django 4.2.7 on 2025-12-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_contractversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractriskanalysis',
            name='category_breakdown',
            field=models.JSONField(blank=True, db_column='categoryBreakdown', default=dict, null=True),
        ),
        migrations.AddField(
            model_name='contractriskanalysis',
            name='detailed_breakdown',
            field=models.JSONField(blank=True, db_column='detailedBreakdown', default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='contractriskanalysis',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_column='riskLevel', max_length=20),
        ),
    ]
