# Generated by Django 4.2.7 on 2025-12-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_risk_scoring_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, db_column='endDate', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='party_a',
            field=models.CharField(blank=True, db_column='partyA', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='party_b',
            field=models.CharField(blank=True, db_column='partyB', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='start_date',
            field=models.DateField(blank=True, db_column='startDate', null=True),
        ),
    ]
