# Generated by Django 4.2.7 on 2025-12-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_contract_end_date_contract_party_a_contract_party_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='jurisdiction',
            field=models.CharField(blank=True, help_text='Contract jurisdiction (e.g., Dubai, USA, UK)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='liability_level',
            field=models.CharField(blank=True, choices=[('LOW', 'Low Liability'), ('MEDIUM', 'Medium Liability'), ('HIGH', 'High Liability')], db_column='liabilityLevel', help_text='Liability level classification', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment_terms',
            field=models.CharField(blank=True, db_column='paymentTerms', help_text='Payment terms (e.g., NET 30, Upon delivery)', max_length=500, null=True),
        ),
    ]
