# Generated by Django 4.2.7 on 2025-12-18 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_search_fields'),
    ]

    operations = [
        migrations.RunSQL(
            # Forward SQL - Create tables with correct char(36) type and collation
            sql="""
            CREATE TABLE `intents` (
                `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL PRIMARY KEY,
                `name` varchar(200) NOT NULL UNIQUE,
                `description` longtext NOT NULL,
                `confidence` double precision NOT NULL,
                `occurrenceCount` integer NOT NULL,
                `createdAt` datetime(6) NOT NULL,
                `updatedAt` datetime(6) NOT NULL
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

            CREATE TABLE `clause_intents` (
                `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL PRIMARY KEY,
                `clause_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
                `intent_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
                `confidence` double precision NOT NULL,
                `isPrimary` bool NOT NULL,
                `createdAt` datetime(6) NOT NULL,
                CONSTRAINT `clause_intents_clause_id_f3a7d123_fk_clauses_id` FOREIGN KEY (`clause_id`) REFERENCES `clauses` (`id`) ON DELETE CASCADE,
                CONSTRAINT `clause_intents_intent_id_ed092d52_fk_intents_id` FOREIGN KEY (`intent_id`) REFERENCES `intents` (`id`) ON DELETE CASCADE,
                UNIQUE KEY `clause_intents_clause_id_intent_id_b72c846a_uniq` (`clause_id`, `intent_id`),
                KEY `clause_inte_clause__7354f9_idx` (`clause_id`, `confidence` DESC),
                KEY `clause_inte_intent__c52df8_idx` (`intent_id`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

            CREATE TABLE `intent_obligations` (
                `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL PRIMARY KEY,
                `clause_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
                `intent_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
                `party` varchar(50) NOT NULL,
                `action` longtext NOT NULL,
                `condition` longtext NULL,
                `deadline` varchar(200) NULL,
                `priority` varchar(20) NOT NULL,
                `riskScore` double precision NOT NULL,
                `createdAt` datetime(6) NOT NULL,
                `updatedAt` datetime(6) NOT NULL,
                CONSTRAINT `intent_obligations_clause_id_dac2ec2c_fk_clauses_id` FOREIGN KEY (`clause_id`) REFERENCES `clauses` (`id`) ON DELETE CASCADE,
                CONSTRAINT `intent_obligations_intent_id_35c66a49_fk_intents_id` FOREIGN KEY (`intent_id`) REFERENCES `intents` (`id`) ON DELETE CASCADE,
                KEY `intent_obli_clause__620cd0_idx` (`clause_id`),
                KEY `intent_obli_intent__beecfa_idx` (`intent_id`),
                KEY `intent_obli_riskSco_548379_idx` (`riskScore` DESC)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

            CREATE TABLE `intent_rights` (
                `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL PRIMARY KEY,
                `clause_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
                `intent_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
                `party` varchar(50) NOT NULL,
                `entitlement` longtext NOT NULL,
                `trigger` longtext NULL,
                `riskScore` double precision NOT NULL,
                `createdAt` datetime(6) NOT NULL,
                `updatedAt` datetime(6) NOT NULL,
                CONSTRAINT `intent_rights_clause_id_4deee601_fk_clauses_id` FOREIGN KEY (`clause_id`) REFERENCES `clauses` (`id`) ON DELETE CASCADE,
                CONSTRAINT `intent_rights_intent_id_3300195b_fk_intents_id` FOREIGN KEY (`intent_id`) REFERENCES `intents` (`id`) ON DELETE CASCADE,
                KEY `intent_righ_clause__c0dab9_idx` (`clause_id`),
                KEY `intent_righ_intent__4a1b73_idx` (`intent_id`),
                KEY `intent_righ_riskSco_fc8b44_idx` (`riskScore` DESC)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
            """,
            # Reverse SQL - Drop tables
            reverse_sql="""
            DROP TABLE IF EXISTS `clause_intents`;
            DROP TABLE IF EXISTS `intent_obligations`;
            DROP TABLE IF EXISTS `intent_rights`;
            DROP TABLE IF EXISTS `intents`;
            """
        ),
    ]
