# Generated by Django 4.2.7 on 2025-12-18 19:54

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_intent_mining_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Canonical intent name', max_length=200, unique=True)),
                ('description', models.TextField(help_text='What this intent means in legal context')),
                ('confidence', models.FloatField(default=0.0, help_text='Overall confidence score for this intent')),
                ('occurrence_count', models.IntegerField(db_column='occurrenceCount', default=0, help_text='Number of clauses with this intent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'intents',
                'ordering': ['-occurrence_count', 'name'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='has_arbitration',
            field=models.BooleanField(db_column='hasArbitration', default=False, help_text='Whether contract includes arbitration clause'),
        ),
        migrations.CreateModel(
            name='IntentRight',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('party', models.CharField(choices=[('YOUR_COMPANY', 'Your Company'), ('COUNTERPARTY', 'Counterparty'), ('BOTH', 'Both Parties')], max_length=50)),
                ('entitlement', models.TextField(help_text='What the party may do')),
                ('trigger', models.TextField(blank=True, help_text='What triggers this right', null=True)),
                ('risk_score', models.FloatField(db_column='riskScore', default=0.0, help_text='Risk score for this right (0-1)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('clause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intent_rights', to='core.clause')),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rights', to='core.intent')),
            ],
            options={
                'db_table': 'intent_rights',
                'ordering': ['-risk_score', 'party'],
                'indexes': [models.Index(fields=['clause'], name='intent_righ_clause__c0dab9_idx'), models.Index(fields=['intent'], name='intent_righ_intent__4a1b73_idx'), models.Index(fields=['-risk_score'], name='intent_righ_riskSco_fc8b44_idx')],
            },
        ),
        migrations.CreateModel(
            name='IntentObligation',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('party', models.CharField(choices=[('YOUR_COMPANY', 'Your Company'), ('COUNTERPARTY', 'Counterparty'), ('BOTH', 'Both Parties')], max_length=50)),
                ('action', models.TextField(help_text='What must be done')),
                ('condition', models.TextField(blank=True, help_text='Under what conditions', null=True)),
                ('deadline', models.CharField(blank=True, help_text='When it must be done', max_length=200, null=True)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=20)),
                ('risk_score', models.FloatField(db_column='riskScore', default=0.0, help_text='Risk score for this obligation (0-1)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('clause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intent_obligations', to='core.clause')),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='core.intent')),
            ],
            options={
                'db_table': 'intent_obligations',
                'ordering': ['-risk_score', '-priority', 'party'],
                'indexes': [models.Index(fields=['clause'], name='intent_obli_clause__620cd0_idx'), models.Index(fields=['intent'], name='intent_obli_intent__beecfa_idx'), models.Index(fields=['-risk_score'], name='intent_obli_riskSco_548379_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClauseIntent',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('confidence', models.FloatField(help_text='Confidence score for this intent assignment (0-1)')),
                ('is_primary', models.BooleanField(db_column='isPrimary', default=False, help_text='Is this the primary intent for the clause')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('clause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clause_intents', to='core.clause')),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clause_intents', to='core.intent')),
            ],
            options={
                'db_table': 'clause_intents',
                'ordering': ['-confidence'],
                'indexes': [models.Index(fields=['clause', '-confidence'], name='clause_inte_clause__7354f9_idx'), models.Index(fields=['intent'], name='clause_inte_intent__c52df8_idx')],
                'unique_together': {('clause', 'intent')},
            },
        ),
    ]
