# Generated by Django 4.2.7 on 2025-12-19 11:07
# Modified to disable FK checks for MySQL compatibility

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_intent_contract_has_arbitration_intentright_and_more'),
    ]

    operations = [
        migrations.RunSQL("SET FOREIGN_KEY_CHECKS=0;", reverse_sql="SET FOREIGN_KEY_CHECKS=1;"),

        migrations.CreateModel(
            name='ComplianceFramework',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('GDPR', 'General Data Protection Regulation'), ('SOX', 'Sarbanes-Oxley Act'), ('HIPAA', 'Health Insurance Portability and Accountability Act'), ('GST', 'Goods and Services Tax / Tax Laws')], help_text='Framework code (GDPR, SOX, HIPAA, GST)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Full framework name', max_length=200)),
                ('description', models.TextField(help_text='What this framework regulates')),
                ('jurisdiction', models.CharField(blank=True, help_text='Primary jurisdiction (e.g., EU, USA, Global)', max_length=100, null=True)),
                ('effective_date', models.DateField(blank=True, db_column='effectiveDate', help_text='Date framework came into effect', null=True)),
                ('version', models.CharField(blank=True, help_text='Framework version/year', max_length=50, null=True)),
                ('is_active', models.BooleanField(db_column='isActive', default=True, help_text='Whether to check this framework')),
                ('priority', models.IntegerField(default=1, help_text='Priority order for checking (1=highest)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'compliance_frameworks',
                'ordering': ['priority', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceRequirement',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('requirement_code', models.CharField(db_column='requirementCode', help_text='Official code (e.g., GDPR Art. 6, SOX Section 404)', max_length=100)),
                ('requirement_name', models.CharField(db_column='requirementName', help_text='Short requirement name', max_length=300)),
                ('description', models.TextField(help_text='Full description of what must be done')),
                ('requirement_type', models.CharField(choices=[('DATA_PROTECTION', 'Data Protection'), ('FINANCIAL_CONTROLS', 'Financial Controls'), ('HEALTH_DATA', 'Health Data Privacy'), ('TAX_COMPLIANCE', 'Tax Compliance'), ('CONSENT', 'Consent Requirements'), ('SECURITY', 'Security Measures'), ('RETENTION', 'Data Retention'), ('BREACH_NOTIFICATION', 'Breach Notification'), ('AUDIT', 'Audit Requirements'), ('REPORTING', 'Reporting Obligations'), ('OTHER', 'Other')], db_column='requirementType', help_text='Category of requirement', max_length=50)),
                ('criticality', models.CharField(choices=[('CRITICAL', 'Critical - Legal mandate'), ('HIGH', 'High - Strong requirement'), ('MEDIUM', 'Medium - Standard requirement'), ('LOW', 'Low - Best practice')], help_text='How critical is compliance with this requirement', max_length=20)),
                ('detection_keywords', models.JSONField(db_column='detectionKeywords', default=list, help_text='Keywords that suggest this requirement applies')),
                ('risk_weight', models.FloatField(db_column='riskWeight', default=1.0, help_text='Multiplier for risk calculations (0.1-2.0)')),
                ('compliance_score_weight', models.FloatField(db_column='complianceScoreWeight', default=1.0, help_text='Weight in overall compliance score')),
                ('legal_reference', models.TextField(blank=True, db_column='legalReference', help_text='Link to official documentation', null=True)),
                ('is_active', models.BooleanField(db_column='isActive', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('framework', models.ForeignKey(db_column='frameworkId', on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='core.complianceframework')),
            ],
            options={
                'db_table': 'compliance_requirements',
                'ordering': ['-criticality', 'requirement_code'],
            },
        ),
        migrations.CreateModel(
            name='ContractComplianceAnalysis',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('overall_compliance_score', models.FloatField(db_column='overallComplianceScore', default=0.0, help_text='Weighted compliance score (0-100)')),
                ('total_requirements_checked', models.IntegerField(db_column='totalRequirementsChecked', default=0)),
                ('compliant_count', models.IntegerField(db_column='compliantCount', default=0)),
                ('partial_count', models.IntegerField(db_column='partialCount', default=0)),
                ('non_compliant_count', models.IntegerField(db_column='nonCompliantCount', default=0)),
                ('framework_scores', models.JSONField(db_column='frameworkScores', default=dict, help_text='{"GDPR": {"score": 75.5, "coverage": 80}, ...}')),
                ('compliance_risk_score', models.FloatField(db_column='complianceRiskScore', default=0.0, help_text='Risk score from non-compliance (0-1)')),
                ('critical_violations', models.IntegerField(db_column='criticalViolations', default=0, help_text='Count of critical compliance failures')),
                ('high_violations', models.IntegerField(db_column='highViolations', default=0)),
                ('medium_violations', models.IntegerField(db_column='mediumViolations', default=0)),
                ('low_violations', models.IntegerField(db_column='lowViolations', default=0)),
                ('executive_summary', models.TextField(blank=True, db_column='executiveSummary', help_text='LLM-generated compliance summary', null=True)),
                ('analysis_completed_at', models.DateTimeField(db_column='analysisCompletedAt')),
                ('analysis_duration_seconds', models.FloatField(db_column='analysisDurationSeconds', default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('contract', models.OneToOneField(db_column='contractId', on_delete=django.db.models.deletion.CASCADE, related_name='compliance_analysis', to='core.contract')),
            ],
            options={
                'db_table': 'contract_compliance_analysis',
                'ordering': ['-analysis_completed_at'],
            },
        ),
        migrations.CreateModel(
            name='IntentComplianceMapping',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('relevance_score', models.FloatField(db_column='relevanceScore', help_text='LLM confidence that requirement applies (0-1)')),
                ('compliance_status', models.CharField(choices=[('COMPLIANT', 'Fully Compliant'), ('PARTIAL', 'Partially Compliant'), ('NON_COMPLIANT', 'Non-Compliant'), ('NOT_APPLICABLE', 'Not Applicable'), ('NEEDS_REVIEW', 'Needs Manual Review')], db_column='complianceStatus', help_text='Whether intent meets the requirement', max_length=20)),
                ('analysis_summary', models.TextField(db_column='analysisSummary', help_text='LLM explanation of why this applies')),
                ('gap_description', models.TextField(blank=True, db_column='gapDescription', help_text='What is missing or non-compliant', null=True)),
                ('recommendation', models.TextField(blank=True, help_text='How to achieve compliance', null=True)),
                ('risk_score', models.FloatField(db_column='riskScore', default=0.0, help_text='Risk score for this non-compliance (0-1)')),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_column='detectedAt')),
                ('last_reviewed_at', models.DateTimeField(blank=True, db_column='lastReviewedAt', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('contract', models.ForeignKey(db_column='contractId', help_text='Contract this mapping applies to', on_delete=django.db.models.deletion.CASCADE, related_name='compliance_mappings', to='core.contract')),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_mappings', to='core.intent')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intent_mappings', to='core.compliancerequirement')),
                ('reviewed_by', models.ForeignKey(blank=True, db_column='reviewedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_reviews', to='core.user')),
            ],
            options={
                'db_table': 'intent_compliance_mappings',
                'ordering': ['-risk_score', '-relevance_score'],
                'indexes': [models.Index(fields=['contract', 'compliance_status'], name='intent_comp_contrac_7ced20_idx'), models.Index(fields=['intent', 'relevance_score'], name='intent_comp_intent__270a1b_idx'), models.Index(fields=['requirement'], name='intent_comp_require_7b539a_idx'), models.Index(fields=['-risk_score'], name='intent_comp_riskSco_71e420_idx')],
                'unique_together': {('intent', 'requirement', 'contract')},
            },
        ),
        migrations.AddIndex(
            model_name='compliancerequirement',
            index=models.Index(fields=['framework', 'is_active'], name='compliance__framewo_8ee9bc_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancerequirement',
            index=models.Index(fields=['requirement_type'], name='compliance__require_8355c1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='compliancerequirement',
            unique_together={('framework', 'requirement_code')},
        ),

        migrations.RunSQL("SET FOREIGN_KEY_CHECKS=1;", reverse_sql="SET FOREIGN_KEY_CHECKS=0;"),
    ]
