# Generated by Django 4.2.7 on 2025-12-19 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_complianceframework_compliancerequirement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clauseintent',
            name='contract_version',
            field=models.ForeignKey(blank=True, db_column='contractVersionId', help_text='Contract version this intent was discovered in', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clause_intents', to='core.contractversion'),
        ),
        migrations.AddField(
            model_name='intentobligation',
            name='contract_version',
            field=models.ForeignKey(blank=True, db_column='contractVersionId', help_text='Contract version this obligation was extracted from', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intent_obligations', to='core.contractversion'),
        ),
        migrations.AddField(
            model_name='intentright',
            name='contract_version',
            field=models.ForeignKey(blank=True, db_column='contractVersionId', help_text='Contract version this right was extracted from', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intent_rights', to='core.contractversion'),
        ),
        migrations.AddIndex(
            model_name='clauseintent',
            index=models.Index(fields=['contract_version', '-confidence'], name='clauseintent_version_conf_idx'),
        ),
        migrations.AddIndex(
            model_name='intentobligation',
            index=models.Index(fields=['contract_version', '-risk_score'], name='intentobl_version_risk_idx'),
        ),
        migrations.AddIndex(
            model_name='intentright',
            index=models.Index(fields=['contract_version', '-risk_score'], name='intentright_version_risk_idx'),
        ),
    ]
