# Generated by Django 4.2.7 on 2025-12-20 08:32

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_version_tracking_to_intents'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClauseRewriteSuggestion',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('original_text', models.TextField(db_column='originalText', help_text='Original clause text')),
                ('suggested_text', models.TextField(db_column='suggestedText', help_text='Suggested rewrite')),
                ('rationale', models.TextField(help_text='Why this change is recommended')),
                ('category', models.CharField(choices=[('RISK_REDUCTION', 'Risk Reduction'), ('CLARITY_IMPROVEMENT', 'Clarity Improvement'), ('FAVORABLE_TERMS', 'More Favorable Terms'), ('COMPLIANCE', 'Compliance Enhancement'), ('MUTUAL_BENEFIT', 'Mutual Benefit'), ('STANDARD_PRACTICE', 'Industry Standard Practice')], max_length=30)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('MODIFIED', 'Modified and Accepted')], default='PENDING', max_length=20)),
                ('impact_analysis', models.TextField(blank=True, db_column='impactAnalysis', help_text='Analysis of how this change affects the contract', null=True)),
                ('negotiation_tips', models.TextField(blank=True, db_column='negotiationTips', help_text='Tips for negotiating this change', null=True)),
                ('confidence_score', models.FloatField(db_column='confidenceScore', default=0.5, help_text='AI confidence in suggestion (0-1)')),
                ('reviewed_at', models.DateTimeField(blank=True, db_column='reviewedAt', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'clause_rewrite_suggestions',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='intentcompliancemapping',
            new_name='intent_comp_intentI_c9931c_idx',
            old_name='intent_comp_intent__270a1b_idx',
        ),
        migrations.RenameIndex(
            model_name='intentcompliancemapping',
            new_name='intent_comp_require_bfb329_idx',
            old_name='intent_comp_require_7b539a_idx',
        ),
        migrations.AlterField(
            model_name='intentcompliancemapping',
            name='intent',
            field=models.ForeignKey(db_column='intentId', on_delete=django.db.models.deletion.CASCADE, related_name='compliance_mappings', to='core.intent'),
        ),
        migrations.AlterField(
            model_name='intentcompliancemapping',
            name='requirement',
            field=models.ForeignKey(db_column='requirementId', on_delete=django.db.models.deletion.CASCADE, related_name='intent_mappings', to='core.compliancerequirement'),
        ),
        migrations.AddField(
            model_name='clauserewritesuggestion',
            name='clause',
            field=models.ForeignKey(db_column='clauseId', on_delete=django.db.models.deletion.CASCADE, related_name='rewrite_suggestions', to='core.clause'),
        ),
        migrations.AddField(
            model_name='clauserewritesuggestion',
            name='contract',
            field=models.ForeignKey(db_column='contractId', on_delete=django.db.models.deletion.CASCADE, related_name='rewrite_suggestions', to='core.contract'),
        ),
        migrations.AddField(
            model_name='clauserewritesuggestion',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='createdBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clause_suggestions', to='core.user'),
        ),
        migrations.AddField(
            model_name='clauserewritesuggestion',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, db_column='reviewedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_suggestions', to='core.user'),
        ),
        migrations.AddIndex(
            model_name='clauserewritesuggestion',
            index=models.Index(fields=['contract', 'status'], name='clause_rewr_contrac_12bc6b_idx'),
        ),
        migrations.AddIndex(
            model_name='clauserewritesuggestion',
            index=models.Index(fields=['clause'], name='clause_rewr_clauseI_0dbcdd_idx'),
        ),
        migrations.AddIndex(
            model_name='clauserewritesuggestion',
            index=models.Index(fields=['status'], name='clause_rewr_status_499018_idx'),
        ),
    ]
