# Generated by Django 4.2.7 on 2025-12-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_negotiation_agent_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='bert_intents',
            field=models.JSONField(blank=True, db_column='bertIntents', help_text='Contracts-BERT intent distribution', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='bert_topics',
            field=models.JSONField(blank=True, db_column='bertTopics', help_text='BERTopic classification results', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='fused_scores',
            field=models.JSONField(blank=True, db_column='fusedScores', help_text='All contract type scores from fusion', null=True),
        ),
    ]
