# Generated by Django 4.2.7 on 2025-12-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_fusion_classification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'Under Review'), ('NEGOTIATION', 'In Negotiation'), ('FINAL', 'Finalized')], default='DRAFT', help_text='Contract workflow status', max_length=20),
        ),
    ]
