# Generated by Django 4.2.7 on 2025-12-24 06:16

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_approval_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='clausedeviation',
            name='accepted_at',
            field=models.DateTimeField(blank=True, db_column='acceptedAt', null=True),
        ),
        migrations.AddField(
            model_name='clausedeviation',
            name='accepted_text',
            field=models.TextField(blank=True, db_column='acceptedText', null=True),
        ),
        migrations.AddField(
            model_name='clausedeviation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('ACCEPTED', 'Suggestion Accepted'), ('REJECTED', 'Suggestion Rejected'), ('MODIFIED', 'Manually Modified')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='clausedeviation',
            name='suggested_text',
            field=models.TextField(blank=True, db_column='suggestedText', null=True),
        ),
        migrations.CreateModel(
            name='ApprovalTask',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('role_required', models.CharField(choices=[('LEGAL', 'Legal Reviewer'), ('BUSINESS', 'Business Owner'), ('COMPLIANCE', 'Compliance Officer'), ('ADMIN', 'Administrator')], db_column='roleRequired', help_text='Role needed to approve', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('comments', models.TextField(blank=True, help_text='Approver comments or rejection reason', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('approved_at', models.DateTimeField(blank=True, db_column='approvedAt', null=True)),
                ('workflow_stage', models.CharField(db_column='workflowStage', help_text='Contract stage when task was created', max_length=30)),
                ('assigned_to', models.ForeignKey(blank=True, db_column='assignedTo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_tasks_assigned', to='core.user')),
                ('contract', models.ForeignKey(db_column='contractId', on_delete=django.db.models.deletion.CASCADE, related_name='approval_tasks', to='core.contract')),
            ],
            options={
                'db_table': 'approval_tasks',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalAudit',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('user_role', models.CharField(db_column='userRole', help_text='Role of user at time of action', max_length=50)),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REASSIGNED', 'Reassigned')], max_length=20)),
                ('comments', models.TextField(help_text='Audit trail comments')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When action was performed')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_column='ipAddress', help_text='IP address of approver', null=True)),
                ('user_agent', models.CharField(blank=True, db_column='userAgent', help_text='Browser/client info', max_length=500, null=True)),
                ('approval_task', models.ForeignKey(db_column='approvalTaskId', on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='core.approvaltask')),
                ('contract', models.ForeignKey(db_column='contractId', on_delete=django.db.models.deletion.CASCADE, related_name='approval_audits', to='core.contract')),
                ('user', models.ForeignKey(db_column='userId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_audits', to='core.user')),
            ],
            options={
                'db_table': 'approval_audits',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='approvaltask',
            index=models.Index(fields=['contract', 'status'], name='approval_ta_contrac_6bbf1f_idx'),
        ),
        migrations.AddIndex(
            model_name='approvaltask',
            index=models.Index(fields=['role_required', 'status'], name='approval_ta_roleReq_f42efd_idx'),
        ),
        migrations.AddIndex(
            model_name='approvaltask',
            index=models.Index(fields=['assigned_to', 'status'], name='approval_ta_assigne_8b3fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalaudit',
            index=models.Index(fields=['contract', '-timestamp'], name='approval_au_contrac_09158a_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalaudit',
            index=models.Index(fields=['user', '-timestamp'], name='approval_au_userId_1d4faa_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalaudit',
            index=models.Index(fields=['approval_task'], name='approval_au_approva_99c048_idx'),
        ),
    ]
