# Generated by Django 4.2.7 on 2025-12-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_clausedeviation_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clause',
            name='clause_label',
            field=models.CharField(blank=True, db_column='clauseLabel', help_text='Cluster label for grouped similar clauses', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clause',
            name='clause_type',
            field=models.CharField(blank=True, db_column='clauseType', help_text='AI-generated clause category (e.g., Payment Terms, Liability)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clause',
            name='embedding_id',
            field=models.CharField(blank=True, db_column='embeddingId', help_text='Reference ID for vector embedding in Qdrant', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='clause',
            index=models.Index(fields=['clause_type'], name='clauses_clauseT_aba8d3_idx'),
        ),
        migrations.AddIndex(
            model_name='clause',
            index=models.Index(fields=['embedding_id'], name='clauses_embeddi_b3a78f_idx'),
        ),
    ]
