# Generated by Django 4.2.7 on 2025-12-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_clause_library_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='clause',
            name='enriched_at',
            field=models.DateTimeField(blank=True, db_column='enrichedAt', help_text='When risk enrichment was performed', null=True),
        ),
        migrations.AddField(
            model_name='clause',
            name='impact_score',
            field=models.FloatField(blank=True, db_column='impactScore', help_text='Severity of risk impact (1-5)', null=True),
        ),
        migrations.AddField(
            model_name='clause',
            name='likelihood_score',
            field=models.FloatField(blank=True, db_column='likelihoodScore', help_text='Probability of risk occurrence (1-5)', null=True),
        ),
        migrations.AddField(
            model_name='clause',
            name='risk_factors',
            field=models.JSONField(blank=True, db_column='riskFactors', default=dict, help_text='Detailed risk factors from enrichment'),
        ),
        migrations.AddField(
            model_name='clause',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], db_column='riskLevel', help_text='Risk severity classification', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clause',
            name='risk_score',
            field=models.FloatField(blank=True, db_column='riskScore', help_text='Enriched risk score from ClauseRiskEnricher (0-1)', null=True),
        ),
        migrations.AddIndex(
            model_name='clause',
            index=models.Index(fields=['risk_level', '-risk_score'], name='clauses_riskLev_83cd12_idx'),
        ),
        migrations.AddIndex(
            model_name='clause',
            index=models.Index(fields=['likelihood_score', 'impact_score'], name='clauses_likelih_6758de_idx'),
        ),
        migrations.AddIndex(
            model_name='clause',
            index=models.Index(fields=['clause_type', 'risk_level'], name='clauses_clauseT_de91a5_idx'),
        ),
    ]
