# Generated by Django 4.2.7 on 2025-12-30 10:44

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_clause_enriched_at_clause_impact_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractIntelligence',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('parties', models.TextField(blank=True, help_text='Entities entering the agreement', null=True)),
                ('termination_summary', models.TextField(blank=True, db_column='terminationSummary', help_text='How contract can be ended', null=True)),
                ('termination_notice_period', models.CharField(blank=True, db_column='terminationNoticePeriod', help_text='Required notice period for termination', max_length=200, null=True)),
                ('liability_summary', models.TextField(blank=True, db_column='liabilitySummary', help_text='Liability limitations and caps', null=True)),
                ('jurisdiction', models.CharField(blank=True, help_text='Governing law jurisdiction', max_length=200, null=True)),
                ('confidentiality_duration', models.CharField(blank=True, db_column='confidentialityDuration', help_text='Confidentiality obligations duration', max_length=200, null=True)),
                ('extraction_confidence', models.FloatField(db_column='extractionConfidence', default=0.0, help_text='Overall extraction quality (0-1)')),
                ('vector_db_chunks', models.IntegerField(db_column='vectorDbChunks', default=0, help_text='Number of chunks in vector DB')),
                ('relevant_chunks_used', models.IntegerField(db_column='relevantChunksUsed', default=0, help_text='Chunks used for extraction')),
                ('raw_extraction_data', models.JSONField(db_column='rawExtractionData', default=dict, help_text='Full JSON from LLM extraction')),
                ('extracted_at', models.DateTimeField(auto_now_add=True, db_column='extractedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('contract', models.OneToOneField(db_column='contractId', on_delete=django.db.models.deletion.CASCADE, related_name='intelligence', to='core.contract')),
            ],
            options={
                'db_table': 'contract_intelligence',
                'ordering': ['-extracted_at'],
            },
        ),
        migrations.CreateModel(
            name='VectorEmbedding',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('embedding_id', models.CharField(db_column='embeddingId', help_text='ID in vector database (ChromaDB)', max_length=255, unique=True)),
                ('chunk_index', models.IntegerField(db_column='chunkIndex', help_text='Order of chunk in document')),
                ('chunk_text', models.TextField(db_column='chunkText', help_text='Original text of this chunk')),
                ('chunk_start_char', models.IntegerField(db_column='chunkStartChar', help_text='Start position in full text')),
                ('chunk_end_char', models.IntegerField(db_column='chunkEndChar', help_text='End position in full text')),
                ('chunk_type', models.CharField(blank=True, db_column='chunkType', help_text='Type of content (clause, obligation, etc.)', max_length=50, null=True)),
                ('embedding_model', models.CharField(db_column='embeddingModel', default='sentence-transformers', help_text='Model used for embedding', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('contract', models.ForeignKey(db_column='contractId', on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='core.contract')),
            ],
            options={
                'db_table': 'vector_embeddings',
                'ordering': ['contract', 'chunk_index'],
                'indexes': [models.Index(fields=['contract', 'chunk_index'], name='vector_embe_contrac_902f64_idx'), models.Index(fields=['embedding_id'], name='vector_embe_embeddi_c864c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlfrescoDocument',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('alfresco_node_id', models.CharField(db_column='alfrescoNodeId', help_text='Alfresco node ID', max_length=255, unique=True)),
                ('alfresco_folder_id', models.CharField(db_column='alfrescoFolderId', help_text='Parent folder ID in Alfresco', max_length=255)),
                ('alfresco_name', models.CharField(db_column='alfrescoName', help_text='Original name in Alfresco', max_length=500)),
                ('alfresco_content_type', models.CharField(db_column='alfrescoContentType', help_text='MIME type from Alfresco', max_length=100)),
                ('alfresco_properties', models.JSONField(db_column='alfrescoProperties', default=dict, help_text='Metadata from Alfresco')),
                ('alfresco_version', models.CharField(blank=True, db_column='alfrescoVersion', help_text='Document version in Alfresco', max_length=50, null=True)),
                ('last_synced_at', models.DateTimeField(db_column='lastSyncedAt', help_text='When document was last synced')),
                ('sync_status', models.CharField(choices=[('SYNCED', 'Synced'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], db_column='syncStatus', default='SYNCED', max_length=20)),
                ('sync_error', models.TextField(blank=True, db_column='syncError', help_text='Error message if sync failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('contract', models.OneToOneField(blank=True, db_column='contractId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alfresco_doc', to='core.contract')),
            ],
            options={
                'db_table': 'alfresco_documents',
                'ordering': ['-last_synced_at'],
                'indexes': [models.Index(fields=['alfresco_node_id'], name='alfresco_do_alfresc_47e664_idx'), models.Index(fields=['alfresco_folder_id'], name='alfresco_do_alfresc_2db4e9_idx'), models.Index(fields=['sync_status'], name='alfresco_do_syncSta_807911_idx')],
            },
        ),
    ]
