# Generated by Django 4.2.7 on 2026-01-05 12:01

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_clauseversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='assigned_by',
            field=models.CharField(blank=True, db_column='assignedBy', help_text='ID of user who assigned this contract', max_length=36, null=True),
        ),
        migrations.CreateModel(
            name='ClauseVersion',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField(db_column='versionNumber', help_text='Sequential version number')),
                ('original_text', models.TextField(db_column='originalText', help_text='Text before this edit')),
                ('modified_text', models.TextField(db_column='modifiedText', help_text='Text after this edit')),
                ('change_description', models.TextField(blank=True, db_column='changeDescription', help_text='User explanation of what was changed', null=True)),
                ('new_risk_score', models.FloatField(blank=True, db_column='newRiskScore', null=True)),
                ('new_risk_level', models.CharField(blank=True, db_column='newRiskLevel', max_length=20, null=True)),
                ('new_likelihood_score', models.FloatField(blank=True, db_column='newLikelihoodScore', null=True)),
                ('new_impact_score', models.FloatField(blank=True, db_column='newImpactScore', null=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True, db_column='modifiedAt')),
                ('approved_by_id', models.CharField(blank=True, db_column='approvedBy', help_text='User ID who approved this change', max_length=36, null=True)),
                ('approved_at', models.DateTimeField(blank=True, db_column='approvedAt', null=True)),
                ('clause', models.ForeignKey(db_column='clauseId', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.clause')),
                ('modified_by', models.ForeignKey(db_column='modifiedBy', on_delete=django.db.models.deletion.PROTECT, related_name='clause_edits', to='core.user')),
            ],
            options={
                'db_table': 'clause_versions',
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['clause', '-version_number'], name='clause_vers_clauseI_f7de73_idx'), models.Index(fields=['modified_by', '-modified_at'], name='clause_vers_modifie_a374f8_idx')],
                'unique_together': {('clause', 'version_number')},
            },
        ),
    ]
