# Generated by Django 4.2.7 on 2026-01-06 05:52

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_add_assigned_by_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Plan name (e.g., Free, Standard, Professional)', max_length=100, unique=True)),
                ('display_name', models.CharField(db_column='displayName', help_text='Display name for UI', max_length=100)),
                ('plan_type', models.CharField(choices=[('FREE', 'Free'), ('STANDARD', 'Standard'), ('PROFESSIONAL', 'Professional'), ('ENTERPRISE', 'Enterprise'), ('ON_PREMISE', 'On-Premise')], db_column='planType', max_length=20, unique=True)),
                ('price_monthly', models.DecimalField(db_column='priceMonthly', decimal_places=2, default=0, help_text='Monthly price in USD', max_digits=10)),
                ('contract_limit', models.IntegerField(db_column='contractLimit', help_text='Maximum contracts allowed (-1 for unlimited)')),
                ('features', models.JSONField(default=list, help_text='List of features included in this plan')),
                ('feature_flags', models.JSONField(db_column='featureFlags', default=dict, help_text='Feature toggles: {"analyse_risks": true, "analyse_intents": false, ...}')),
                ('description', models.TextField(blank=True, help_text='Plan description for display', null=True)),
                ('is_active', models.BooleanField(db_column='isActive', default=True, help_text='Whether this plan is available for selection')),
                ('is_contact_sales', models.BooleanField(db_column='isContactSales', default=False, help_text='Whether this requires contacting sales')),
                ('sort_order', models.IntegerField(db_column='sortOrder', default=0, help_text='Display order (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'pricing_plans',
                'ordering': ['sort_order', 'price_monthly'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='current_plan',
            field=models.ForeignKey(blank=True, db_column='currentPlanId', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.pricingplan'),
        ),
    ]
