# Generated by Django 4.2.7 on 2026-01-07 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_add_analysis_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_contracts_uploaded',
            field=models.IntegerField(db_column='totalContractsUploaded', default=0, help_text='Lifetime count of contracts uploaded (never decreases)'),
        ),
    ]
