# Generated by Django 4.2.7 on 2026-01-12 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_add_payment_subscription_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('executive_summary', models.TextField(blank=True, db_column='executiveSummary', help_text='AI-generated high-level summary for executives', null=True)),
                ('risk_score', models.IntegerField(blank=True, db_column='riskScore', help_text='Overall risk score 0-100', null=True)),
                ('risk_level', models.CharField(blank=True, choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], db_column='riskLevel', help_text='Risk classification', max_length=20, null=True)),
                ('risk_flags', models.JSONField(blank=True, db_column='riskFlags', default=list, help_text='List of specific risk factors identified')),
                ('extracted_clauses', models.JSONField(blank=True, db_column='extractedClauses', default=dict, help_text='Extracted provisions: {"liability": "...", "payment": "..."}')),
                ('agent_metadata', models.JSONField(blank=True, db_column='agentMetadata', default=dict, help_text='Agent metadata: {"primary_intent": "...", "confidence": 0.98}')),
                ('primary_intent', models.CharField(blank=True, db_column='primaryIntent', help_text='Main business intent (extracted for search)', max_length=200, null=True)),
                ('intent_confidence', models.FloatField(blank=True, db_column='intentConfidence', help_text='Confidence score for intent classification (0-1)', null=True)),
                ('is_compliant', models.BooleanField(db_column='isCompliant', default=True, help_text='Overall compliance status')),
                ('compliance_issues', models.JSONField(blank=True, db_column='complianceIssues', default=list, help_text='List of compliance violations found')),
                ('agent_version', models.CharField(db_column='agentVersion', default='1.0', help_text='Version of agent that performed analysis', max_length=50)),
                ('tools_used', models.JSONField(blank=True, db_column='toolsUsed', default=list, help_text='List of MCP tools used in this analysis')),
                ('execution_time_seconds', models.FloatField(blank=True, db_column='executionTimeSeconds', help_text='Time taken for agent to complete analysis', null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, db_column='analyzedAt', help_text='When this analysis was performed')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt', help_text='When this analysis was last updated')),
                ('contract', models.ForeignKey(db_column='contractId', help_text='Contract this analysis belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='core.contract')),
            ],
            options={
                'db_table': 'analysis_results',
                'ordering': ['-analyzed_at'],
                'indexes': [models.Index(fields=['contract'], name='analysis_re_contrac_4d2091_idx'), models.Index(fields=['risk_score'], name='analysis_re_riskSco_7fd1dc_idx'), models.Index(fields=['risk_level'], name='analysis_re_riskLev_4d075c_idx'), models.Index(fields=['primary_intent'], name='analysis_re_primary_197d23_idx'), models.Index(fields=['-analyzed_at'], name='analysis_re_analyze_02f91f_idx')],
            },
        ),
    ]
