# Generated by Django 4.2.7 on 2026-01-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_analysisresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fivetran_access',
            field=models.BooleanField(db_column='fivetranAccess', default=False, help_text='User has access to Fivetran connector features'),
        ),
        migrations.AddField(
            model_name='user',
            name='kafka_access',
            field=models.BooleanField(db_column='kafkaAccess', default=False, help_text='User has access to Kafka connector features'),
        ),
    ]
