# Generated by Django 4.2.7 on 2026-01-19 07:07

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_add_redline_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedlineChange',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('clause_name', models.CharField(db_column='clauseName', max_length=255)),
                ('clause_index', models.IntegerField(db_column='clauseIndex', default=0, help_text='Order in the document')),
                ('original_text', models.TextField(db_column='originalText')),
                ('suggested_text', models.TextField(db_column='suggestedText')),
                ('accepted_text', models.TextField(blank=True, db_column='acceptedText', help_text='Final text after user edits', null=True)),
                ('redline_diff', models.TextField(blank=True, db_column='redlineDiff', null=True)),
                ('risk_type', models.CharField(choices=[('FINANCIAL', 'Financial Risk'), ('LIABILITY', 'Liability Risk'), ('TERMINATION', 'Termination Risk'), ('IP', 'Intellectual Property Risk'), ('CONFIDENTIALITY', 'Confidentiality Risk'), ('GOVERNING_LAW', 'Governing Law Risk'), ('INDEMNITY', 'Indemnification Risk'), ('FORCE_MAJEURE', 'Force Majeure Risk'), ('DATA_PRIVACY', 'Data Privacy Risk'), ('COMPLIANCE', 'Compliance Risk'), ('OTHER', 'Other Risk')], db_column='riskType', max_length=30)),
                ('risk_score', models.IntegerField(db_column='riskScore', default=0, help_text='Risk score 0-100')),
                ('risk_explanation', models.TextField(db_column='riskExplanation', help_text='Commercial risk explanation')),
                ('legal_doctrine', models.CharField(blank=True, db_column='legalDoctrine', help_text='Legal doctrine violated (e.g., Unconscionability)', max_length=255, null=True)),
                ('court_reasoning', models.TextField(blank=True, db_column='courtReasoning', help_text='Why courts typically reject this clause', null=True)),
                ('litigation_risk', models.CharField(blank=True, db_column='litigationRisk', help_text='Probability of judicial modification', max_length=100, null=True)),
                ('judicial_treatment', models.TextField(blank=True, db_column='judicialTreatment', help_text='How courts usually interpret this clause', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('MODIFIED', 'Modified')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, db_column='reviewedAt', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'redline_changes',
                'ordering': ['clause_index', '-risk_score'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RedlineSession',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('EXPORTED', 'Exported')], default='IN_PROGRESS', max_length=20)),
                ('jurisdiction', models.CharField(default='Common Law', help_text='Legal jurisdiction for analysis', max_length=100)),
                ('total_clauses_analyzed', models.IntegerField(db_column='totalClausesAnalyzed', default=0)),
                ('high_risk_count', models.IntegerField(db_column='highRiskCount', default=0)),
                ('medium_risk_count', models.IntegerField(db_column='mediumRiskCount', default=0)),
                ('low_risk_count', models.IntegerField(db_column='lowRiskCount', default=0)),
                ('changes_accepted', models.IntegerField(db_column='changesAccepted', default=0)),
                ('changes_rejected', models.IntegerField(db_column='changesRejected', default=0)),
                ('docx_exported_at', models.DateTimeField(blank=True, db_column='docxExportedAt', null=True)),
                ('pdf_exported_at', models.DateTimeField(blank=True, db_column='pdfExportedAt', null=True)),
                ('exported_file_path', models.TextField(blank=True, db_column='exportedFilePath', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('completed_at', models.DateTimeField(blank=True, db_column='completedAt', null=True)),
            ],
            options={
                'db_table': 'redline_sessions',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
    ]
