# Generated by Django 4.2.7 on 2026-01-19 08:13

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_redlinechange_redlinesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskPlaybook',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('risk_type', models.CharField(choices=[('LIABILITY', 'Liability Risk'), ('TERMINATION', 'Termination Risk'), ('INDEMNIFICATION', 'Indemnification Risk'), ('IP_OWNERSHIP', 'IP Ownership Risk'), ('CONFIDENTIALITY', 'Confidentiality Risk'), ('PAYMENT', 'Payment Risk'), ('GOVERNING_LAW', 'Governing Law Risk'), ('FORCE_MAJEURE', 'Force Majeure Risk'), ('DATA_PRIVACY', 'Data Privacy Risk'), ('NON_COMPETE', 'Non-Compete Risk'), ('LIMITATION_OF_DAMAGES', 'Limitation of Damages'), ('ASSIGNMENT', 'Assignment Risk'), ('RENEWAL', 'Auto-Renewal Risk'), ('DISPUTE_RESOLUTION', 'Dispute Resolution Risk'), ('OTHER', 'Other Risk')], db_column='riskType', help_text='Category of risk this pattern represents', max_length=50)),
                ('risk_name', models.CharField(db_column='riskName', help_text='Short name for this risk pattern', max_length=255)),
                ('risk_description', models.TextField(db_column='riskDescription', help_text='Full description of the risky pattern')),
                ('example_clause_text', models.TextField(db_column='exampleClauseText', help_text='Example text of a clause exhibiting this risk')),
                ('severity_weight', models.FloatField(db_column='severityWeight', default=0.5, help_text='Severity multiplier (0.0-1.0) for risk scoring')),
                ('embedding', models.JSONField(blank=True, default=list, help_text='Pre-computed 384-dim embedding vector as JSON array')),
                ('embedding_model', models.CharField(db_column='embeddingModel', default='all-MiniLM-L6-v2', help_text='Model used to generate embedding', max_length=100)),
                ('similarity_threshold', models.FloatField(db_column='similarityThreshold', default=0.7, help_text='Minimum cosine similarity to trigger this risk')),
                ('jurisdiction', models.CharField(blank=True, help_text='Jurisdiction where this risk is most relevant', max_length=100, null=True)),
                ('legal_reference', models.TextField(blank=True, db_column='legalReference', help_text='Legal precedent or regulation reference', null=True)),
                ('court_treatment', models.TextField(blank=True, db_column='courtTreatment', help_text='How courts typically treat this clause type', null=True)),
                ('is_active', models.BooleanField(db_column='isActive', default=True, help_text='Whether this risk pattern is actively checked')),
                ('created_by_id', models.CharField(blank=True, db_column='createdBy', help_text='ID of user who created this playbook', max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'risk_playbooks',
                'ordering': ['-severity_weight', 'risk_type'],
                'indexes': [models.Index(fields=['risk_type', 'is_active'], name='risk_playbo_riskTyp_7082df_idx'), models.Index(fields=['-severity_weight'], name='risk_playbo_severit_17275a_idx'), models.Index(fields=['jurisdiction'], name='risk_playbo_jurisdi_4c7608_idx')],
            },
        ),
        migrations.CreateModel(
            name='IntentTemplate',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('intent_name', models.CharField(db_column='intentName', help_text='Canonical name for this intent', max_length=255, unique=True)),
                ('intent_category', models.CharField(choices=[('LIABILITY_SHIFT', 'Liability Shifting'), ('DAMAGE_EXCLUSION', 'Damage Exclusion'), ('TERMINATION_CONTROL', 'Termination Control'), ('IP_TRANSFER', 'IP Transfer'), ('PAYMENT_CONTROL', 'Payment Control'), ('CONFIDENTIALITY_OBLIGATION', 'Confidentiality Obligation'), ('NON_COMPETE', 'Non-Compete Restriction'), ('INDEMNIFICATION', 'Indemnification Obligation'), ('DISPUTE_RESOLUTION', 'Dispute Resolution'), ('RENEWAL_CONTROL', 'Renewal/Extension Control'), ('ASSIGNMENT_RESTRICTION', 'Assignment Restriction'), ('GOVERNING_LAW', 'Governing Law Selection'), ('COMPLIANCE_REQUIREMENT', 'Compliance Requirement'), ('DATA_HANDLING', 'Data Handling Obligation'), ('OTHER', 'Other Intent')], db_column='intentCategory', help_text='Category of legal intent', max_length=50)),
                ('intent_description', models.TextField(db_column='intentDescription', help_text='What this intent aims to achieve legally')),
                ('example_clause_text', models.TextField(db_column='exampleClauseText', help_text='Example clause text that exhibits this intent')),
                ('party_impact', models.CharField(choices=[('FAVOR_YOU', 'Favors Your Company'), ('FAVOR_COUNTERPARTY', 'Favors Counterparty'), ('NEUTRAL', 'Neutral/Balanced'), ('MUTUAL', 'Mutual Obligation')], db_column='partyImpact', help_text='Which party does this intent favor', max_length=30)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], db_column='riskLevel', default='MEDIUM', help_text='Inherent risk level of this intent', max_length=20)),
                ('embedding', models.JSONField(blank=True, default=list, help_text='Pre-computed 384-dim embedding vector as JSON array')),
                ('embedding_model', models.CharField(db_column='embeddingModel', default='all-MiniLM-L6-v2', help_text='Model used to generate embedding', max_length=100)),
                ('similarity_threshold', models.FloatField(db_column='similarityThreshold', default=0.65, help_text='Minimum cosine similarity to detect this intent')),
                ('negotiation_guidance', models.TextField(blank=True, db_column='negotiationGuidance', help_text='How to negotiate when this intent is detected', null=True)),
                ('risk_mitigation', models.TextField(blank=True, db_column='riskMitigation', help_text='How to mitigate risks from this intent', null=True)),
                ('is_active', models.BooleanField(db_column='isActive', default=True, help_text='Whether this intent is actively detected')),
                ('created_by_id', models.CharField(blank=True, db_column='createdBy', help_text='ID of user who created this template', max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'intent_templates',
                'ordering': ['intent_category', 'intent_name'],
                'indexes': [models.Index(fields=['intent_category', 'is_active'], name='intent_temp_intentC_6a7994_idx'), models.Index(fields=['party_impact'], name='intent_temp_partyIm_b39791_idx'), models.Index(fields=['risk_level'], name='intent_temp_riskLev_b22f60_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClauseEmbedding',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('clause_id', models.CharField(db_column='clauseId', help_text='Clause ID this embedding belongs to', max_length=36, unique=True)),
                ('embedding', models.JSONField(default=list, help_text='384-dim embedding vector as JSON array')),
                ('embedding_model', models.CharField(db_column='embeddingModel', default='all-MiniLM-L6-v2', max_length=100)),
                ('embedded_text_hash', models.CharField(db_column='embeddedTextHash', help_text='SHA256 hash of embedded text for change detection', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'clause_embeddings',
                'indexes': [models.Index(fields=['clause_id'], name='clause_embe_clauseI_e183bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApprovedClause',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('clause_type', models.CharField(choices=[('LIABILITY', 'Liability Clause'), ('INDEMNIFICATION', 'Indemnification Clause'), ('TERMINATION', 'Termination Clause'), ('CONFIDENTIALITY', 'Confidentiality Clause'), ('IP_OWNERSHIP', 'IP Ownership Clause'), ('PAYMENT', 'Payment Terms'), ('GOVERNING_LAW', 'Governing Law'), ('DISPUTE_RESOLUTION', 'Dispute Resolution'), ('FORCE_MAJEURE', 'Force Majeure'), ('DATA_PROTECTION', 'Data Protection'), ('NON_COMPETE', 'Non-Compete'), ('ASSIGNMENT', 'Assignment'), ('RENEWAL', 'Renewal Terms'), ('WARRANTY', 'Warranty'), ('LIMITATION_OF_DAMAGES', 'Limitation of Damages'), ('OTHER', 'Other')], db_column='clauseType', help_text='Type of clause', max_length=50)),
                ('clause_name', models.CharField(db_column='clauseName', help_text='Descriptive name for this approved clause', max_length=255)),
                ('intent_name', models.CharField(db_column='intentName', help_text='Intent this clause addresses (matches IntentTemplate.intent_name)', max_length=255)),
                ('intent_template_id', models.CharField(blank=True, db_column='intentTemplateId', help_text='Optional ID of IntentTemplate for direct lookup', max_length=36, null=True)),
                ('clause_text', models.TextField(db_column='clauseText', help_text='The approved, legally-vetted clause text')),
                ('protection_level', models.CharField(choices=[('MAXIMUM', 'Maximum Protection'), ('BALANCED', 'Balanced/Market Standard'), ('MINIMUM', 'Minimum Acceptable')], db_column='protectionLevel', help_text='Level of protection this clause provides', max_length=20)),
                ('jurisdiction', models.CharField(default='Common Law', help_text='Jurisdiction this clause is designed for', max_length=100)),
                ('contract_types', models.JSONField(db_column='contractTypes', default=list, help_text='Contract types this clause applies to (e.g., ["NDA", "SLA", "MSA"])')),
                ('embedding', models.JSONField(blank=True, default=list, help_text='Pre-computed 384-dim embedding for similarity search')),
                ('embedding_model', models.CharField(db_column='embeddingModel', default='all-MiniLM-L6-v2', help_text='Model used to generate embedding', max_length=100)),
                ('legal_notes', models.TextField(blank=True, db_column='legalNotes', help_text='Legal team notes on this clause', null=True)),
                ('last_reviewed_by_id', models.CharField(blank=True, db_column='lastReviewedBy', help_text='ID of user who last reviewed this clause', max_length=36, null=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, db_column='lastReviewedAt', null=True)),
                ('is_active', models.BooleanField(db_column='isActive', default=True, help_text='Whether this clause is available for suggestions')),
                ('version', models.IntegerField(default=1, help_text='Version number of this approved clause')),
                ('created_by_id', models.CharField(blank=True, db_column='createdBy', help_text='ID of user who created this clause', max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'approved_clauses',
                'ordering': ['clause_type', 'protection_level', 'clause_name'],
                'indexes': [models.Index(fields=['clause_type', 'is_active'], name='approved_cl_clauseT_9591c5_idx'), models.Index(fields=['intent_name'], name='approved_cl_intentN_6f5a64_idx'), models.Index(fields=['jurisdiction'], name='approved_cl_jurisdi_2dd005_idx'), models.Index(fields=['protection_level'], name='approved_cl_protect_0fff81_idx')],
            },
        ),
    ]
