# Generated by Django 4.2.7 on 2026-01-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037b_create_missing_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clausedeviationscore',
            options={},
        ),
        migrations.AlterModelOptions(
            name='contractriskhistory',
            options={'ordering': ['contract_id', 'version']},
        ),
        migrations.AlterModelOptions(
            name='expectedobligation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='goldstandardtemplate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='industrybenchmark',
            options={},
        ),
        migrations.AlterModelOptions(
            name='missingsafeguarddetection',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='clausedeviationscore',
            name='clause_devi_clauseI_247023_idx',
        ),
        migrations.RemoveIndex(
            model_name='expectedobligation',
            name='expected_ob_obligat_252b79_idx',
        ),
        migrations.RemoveIndex(
            model_name='expectedobligation',
            name='expected_ob_critica_5eed0d_idx',
        ),
        migrations.RemoveIndex(
            model_name='industrybenchmark',
            name='industry_be_clauseC_62338b_idx',
        ),
        migrations.RemoveIndex(
            model_name='industrybenchmark',
            name='industry_be_industr_313d87_idx',
        ),
        migrations.RemoveIndex(
            model_name='missingsafeguarddetection',
            name='missing_saf_contrac_f5cc72_idx',
        ),
        migrations.RemoveIndex(
            model_name='missingsafeguarddetection',
            name='missing_saf_status_29b27e_idx',
        ),
        migrations.AlterUniqueTogether(
            name='clausedeviationscore',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='missingsafeguarddetection',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='goldstandardtemplate',
            name='created_by_id',
        ),
        migrations.AddField(
            model_name='goldstandardtemplate',
            name='created_by',
            field=models.CharField(blank=True, db_column='createdBy', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='clausedeviationscore',
            name='clause_id',
            field=models.CharField(db_column='clauseId', max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='clausedeviationscore',
            name='contract_id',
            field=models.CharField(db_column='contractId', db_index=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='clausedeviationscore',
            name='court_precedent',
            field=models.TextField(blank=True, db_column='courtPrecedent', null=True),
        ),
        migrations.AlterField(
            model_name='clausedeviationscore',
            name='explanation',
            field=models.TextField(blank=True, help_text='Why this clause deviates', null=True),
        ),
        migrations.AlterField(
            model_name='clausedeviationscore',
            name='gold_standard_id',
            field=models.CharField(blank=True, db_column='goldStandardId', db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='clausedeviationscore',
            name='gold_standard_similarity',
            field=models.FloatField(blank=True, db_column='goldStandardSimilarity', null=True),
        ),
        migrations.AlterField(
            model_name='clausedeviationscore',
            name='industry_benchmark_id',
            field=models.CharField(blank=True, db_column='industryBenchmarkId', db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='clausedeviationscore',
            name='industry_benchmark_similarity',
            field=models.FloatField(blank=True, db_column='industryBenchmarkSimilarity', null=True),
        ),
        migrations.AlterField(
            model_name='clausedeviationscore',
            name='overall_risk_level',
            field=models.CharField(db_column='overallRiskLevel', db_index=True, help_text='LOW, MEDIUM, HIGH', max_length=20),
        ),
        migrations.AlterField(
            model_name='clausedeviationscore',
            name='past_accepted_similarity',
            field=models.FloatField(blank=True, db_column='pastAcceptedSimilarity', null=True),
        ),
        migrations.AlterField(
            model_name='clausedeviationscore',
            name='risk_type',
            field=models.CharField(blank=True, db_column='riskType', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clausedeviationscore',
            name='suggested_from_template_id',
            field=models.CharField(blank=True, db_column='suggestedFromTemplateId', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='clausedeviationscore',
            name='suggested_replacement_text',
            field=models.TextField(blank=True, db_column='suggestedReplacementText', null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='business_unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='total_liability',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='contract',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='contract',
            name='version_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractriskhistory',
            name='geography_risk',
            field=models.FloatField(db_column='geographyRisk', default=0, help_text='Geography risk score (0-100)'),
        ),
        migrations.AlterField(
            model_name='contractriskhistory',
            name='ip_risk',
            field=models.FloatField(db_column='ipRisk', default=0, help_text='IP risk score (0-100)'),
        ),
        migrations.AlterField(
            model_name='contractriskhistory',
            name='liability_risk',
            field=models.FloatField(db_column='liabilityRisk', default=0, help_text='Liability risk score (0-100)'),
        ),
        migrations.AlterField(
            model_name='contractriskhistory',
            name='overall_risk',
            field=models.FloatField(db_column='overallRisk', help_text='Overall risk score (0-100)'),
        ),
        migrations.AlterField(
            model_name='contractriskhistory',
            name='version',
            field=models.IntegerField(db_column='version', help_text='Contract version number'),
        ),
        migrations.AlterField(
            model_name='expectedobligation',
            name='absence_risk_description',
            field=models.TextField(db_column='absenceRiskDescription', help_text='What risk occurs if this is missing'),
        ),
        migrations.AlterField(
            model_name='expectedobligation',
            name='absence_risk_example',
            field=models.TextField(blank=True, db_column='absenceRiskExample', null=True),
        ),
        migrations.AlterField(
            model_name='expectedobligation',
            name='contract_type',
            field=models.CharField(blank=True, db_column='contractType', db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expectedobligation',
            name='criticality',
            field=models.CharField(db_column='criticality', db_index=True, help_text='CRITICAL, HIGH, MEDIUM, LOW', max_length=20),
        ),
        migrations.AlterField(
            model_name='expectedobligation',
            name='embedding',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='expectedobligation',
            name='embedding_model',
            field=models.CharField(db_column='embeddingModel', max_length=100),
        ),
        migrations.AlterField(
            model_name='expectedobligation',
            name='expected_clause_text',
            field=models.TextField(db_column='expectedClauseText', help_text='Example text of what we expect to see'),
        ),
        migrations.AlterField(
            model_name='expectedobligation',
            name='obligation_category',
            field=models.CharField(db_column='obligationCategory', db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='expectedobligation',
            name='obligation_name',
            field=models.CharField(db_column='obligationName', max_length=255),
        ),
        migrations.AlterField(
            model_name='expectedobligation',
            name='party_protected',
            field=models.CharField(blank=True, db_column='partyProtected', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expectedobligation',
            name='presence_threshold',
            field=models.FloatField(db_column='presenceThreshold', help_text='Similarity threshold to consider obligation present'),
        ),
        migrations.AlterField(
            model_name='expectedobligation',
            name='suggested_clause_text',
            field=models.TextField(blank=True, db_column='suggestedClauseText', null=True),
        ),
        migrations.AlterField(
            model_name='goldstandardtemplate',
            name='approved_clause_text',
            field=models.TextField(db_column='approvedClauseText'),
        ),
        migrations.AlterField(
            model_name='goldstandardtemplate',
            name='clause_category',
            field=models.CharField(db_column='clauseCategory', db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='goldstandardtemplate',
            name='embedding',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='goldstandardtemplate',
            name='embedding_model',
            field=models.CharField(db_column='embeddingModel', max_length=100),
        ),
        migrations.AlterField(
            model_name='goldstandardtemplate',
            name='jurisdiction',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='goldstandardtemplate',
            name='legal_notes',
            field=models.TextField(blank=True, db_column='legalNotes', null=True),
        ),
        migrations.AlterField(
            model_name='goldstandardtemplate',
            name='review_threshold',
            field=models.FloatField(db_column='reviewThreshold', help_text='Similarity threshold requiring review'),
        ),
        migrations.AlterField(
            model_name='goldstandardtemplate',
            name='safe_threshold',
            field=models.FloatField(db_column='safeThreshold', help_text='Similarity threshold for safe clauses'),
        ),
        migrations.AlterField(
            model_name='goldstandardtemplate',
            name='template_name',
            field=models.CharField(db_column='templateName', max_length=255),
        ),
        migrations.AlterField(
            model_name='industrybenchmark',
            name='adoption_rate',
            field=models.FloatField(db_column='adoptionRate', help_text='How common this clause is (0-1)'),
        ),
        migrations.AlterField(
            model_name='industrybenchmark',
            name='benchmark_clause_text',
            field=models.TextField(db_column='benchmarkClauseText'),
        ),
        migrations.AlterField(
            model_name='industrybenchmark',
            name='benchmark_name',
            field=models.CharField(db_column='benchmarkName', max_length=255),
        ),
        migrations.AlterField(
            model_name='industrybenchmark',
            name='clause_category',
            field=models.CharField(db_column='clauseCategory', db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='industrybenchmark',
            name='embedding',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='industrybenchmark',
            name='embedding_model',
            field=models.CharField(db_column='embeddingModel', max_length=100),
        ),
        migrations.AlterField(
            model_name='industrybenchmark',
            name='industry',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='industrybenchmark',
            name='jurisdiction',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='industrybenchmark',
            name='source',
            field=models.CharField(blank=True, help_text='Source of benchmark data', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='missingsafeguarddetection',
            name='ai_insight',
            field=models.TextField(db_column='aiInsight', help_text='AI explanation of the detection'),
        ),
        migrations.AlterField(
            model_name='missingsafeguarddetection',
            name='confidence',
            field=models.FloatField(help_text='Confidence in this detection (0-1)'),
        ),
        migrations.AlterField(
            model_name='missingsafeguarddetection',
            name='contract_id',
            field=models.CharField(db_column='contractId', db_index=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='missingsafeguarddetection',
            name='expected_obligation_id',
            field=models.CharField(db_column='expectedObligationId', db_index=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='missingsafeguarddetection',
            name='matched_clause_id',
            field=models.CharField(blank=True, db_column='matchedClauseId', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='missingsafeguarddetection',
            name='matched_similarity',
            field=models.FloatField(blank=True, db_column='matchedSimilarity', null=True),
        ),
        migrations.AlterField(
            model_name='missingsafeguarddetection',
            name='risk_explanation',
            field=models.TextField(db_column='riskExplanation'),
        ),
        migrations.AlterField(
            model_name='missingsafeguarddetection',
            name='status',
            field=models.CharField(db_column='status', db_index=True, help_text='MISSING, WEAK, PRESENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='missingsafeguarddetection',
            name='suggested_action',
            field=models.TextField(db_column='suggestedAction'),
        ),
        migrations.AlterField(
            model_name='missingsafeguarddetection',
            name='suggested_clause_text',
            field=models.TextField(blank=True, db_column='suggestedClauseText', null=True),
        ),
        migrations.AddIndex(
            model_name='clausedeviationscore',
            index=models.Index(fields=['gold_standard_id'], name='clause_devi_goldSta_f05c7d_idx'),
        ),
        migrations.AddIndex(
            model_name='clausedeviationscore',
            index=models.Index(fields=['industry_benchmark_id'], name='clause_devi_industr_63d5c9_idx'),
        ),
        migrations.AddIndex(
            model_name='contractriskhistory',
            index=models.Index(fields=['contract_id', 'version'], name='contract_ri_contrac_021e01_idx'),
        ),
        migrations.AddIndex(
            model_name='expectedobligation',
            index=models.Index(fields=['obligation_category', 'criticality'], name='expected_ob_obligat_c22d6c_idx'),
        ),
        migrations.AddIndex(
            model_name='industrybenchmark',
            index=models.Index(fields=['clause_category', 'industry'], name='industry_be_clauseC_c71d1b_idx'),
        ),
        migrations.AddIndex(
            model_name='missingsafeguarddetection',
            index=models.Index(fields=['contract_id', 'status'], name='missing_saf_contrac_3d6c0c_idx'),
        ),
        migrations.AddIndex(
            model_name='missingsafeguarddetection',
            index=models.Index(fields=['expected_obligation_id'], name='missing_saf_expecte_f7e560_idx'),
        ),
    ]
