# Generated by Django 4.2.7 on 2026-01-27 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_add_bu_version_risk_history'),
        ('core', '0038_alter_clausedeviationscore_options_and_more'),
    ]

    operations = [
    ]
