# Generated by Django 4.2.7 on 2026-02-04 11:04

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_playbook_automation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractGraphMeta',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('graph_summary', models.JSONField(db_column='graphSummary', help_text='NetworkX graph structure (nodes/edges/metrics)')),
                ('risk_timeline', models.JSONField(db_column='riskTimeline', help_text='Risk propagation timeline with steps and hotspots')),
                ('negotiation_advice', models.JSONField(db_column='negotiationAdvice', help_text='Prioritized negotiation recommendations')),
                ('neo4j_synced', models.BooleanField(db_column='neo4jSynced', default=False, help_text='Whether contract was synced to Neo4j knowledge graph')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'contract_graph_meta',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('active_embedding_model', models.CharField(db_column='activeEmbeddingModel', default='minilm', help_text='Currently active embedding model key', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
            },
        ),
        migrations.RemoveIndex(
            model_name='missingsafeguarddetection',
            name='missing_saf_expecte_c7edd4_idx',
        ),
        migrations.RenameIndex(
            model_name='clauseplaybookresult',
            new_name='clause_play_clauseI_3db13d_idx',
            old_name='clause_play_clauseI_idx003',
        ),
        migrations.RenameIndex(
            model_name='clauseplaybookresult',
            new_name='clause_play_isStand_4f4af0_idx',
            old_name='clause_play_isStand_idx004',
        ),
        migrations.RenameIndex(
            model_name='legalplaybook',
            new_name='legal_playb_clauseT_832f60_idx',
            old_name='legal_playb_clauseT_idx001',
        ),
        migrations.RenameIndex(
            model_name='legalplaybook',
            new_name='legal_playb_mandato_4dece3_idx',
            old_name='legal_playb_mandato_idx002',
        ),
        migrations.RenameIndex(
            model_name='playbookdriftsnapshot',
            new_name='playbook_dr_clauseT_931251_idx',
            old_name='playbook_dr_clauseT_idx005',
        ),
        migrations.RenameIndex(
            model_name='playbookupdatesuggestion',
            new_name='playbook_up_status_87f760_idx',
            old_name='playbook_up_status_idx006',
        ),
        migrations.AlterField(
            model_name='clausedeviationscore',
            name='overall_deviation_score',
            field=models.FloatField(db_column='overallDeviationScore', help_text='Combined deviation score (0-1)'),
        ),
        migrations.AlterField(
            model_name='clauseplaybookresult',
            name='id',
            field=models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='legalplaybook',
            name='id',
            field=models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playbookdriftsnapshot',
            name='id',
            field=models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playbookupdatesuggestion',
            name='id',
            field=models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='clausedeviationscore',
            index=models.Index(fields=['contract_id'], name='clause_devi_contrac_342baa_idx'),
        ),
        migrations.AddIndex(
            model_name='clausedeviationscore',
            index=models.Index(fields=['overall_risk_level'], name='clause_devi_overall_0df0e2_idx'),
        ),
        migrations.AddField(
            model_name='contractgraphmeta',
            name='contract',
            field=models.OneToOneField(db_column='contractId', on_delete=django.db.models.deletion.CASCADE, related_name='graph_meta', to='core.contract'),
        ),
        migrations.AddIndex(
            model_name='contractgraphmeta',
            index=models.Index(fields=['contract_id'], name='contract_gr_contrac_5ab6de_idx'),
        ),
    ]
