# Generated by Django 4.2.7 on 2026-02-09 07:29

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_contractgraphmeta_systemsettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClauseHealthMetrics',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('usage_count', models.IntegerField(db_column='usageCount', default=0, help_text='Number of times used')),
                ('success_rate', models.FloatField(db_column='successRate', default=0.0, help_text='Success rate (0-1)')),
                ('enforceability_score', models.FloatField(db_column='enforceabilityScore', default=0.5, help_text='Court enforceability (0-1)')),
                ('negotiation_score', models.FloatField(db_column='negotiationScore', default=0.5, help_text='Ease of negotiation (0-1)')),
                ('health_score', models.FloatField(db_column='healthScore', default=0.5, help_text='Overall health (0-1)')),
                ('status', models.CharField(choices=[('ALIVE', 'Alive - Healthy & Active'), ('WEAK', 'Weak - Needs Attention'), ('RETIRED', 'Retired - No Longer Used')], default='ALIVE', help_text='Current health status', max_length=20)),
                ('is_promoted', models.BooleanField(db_column='isPromoted', default=False)),
                ('promoted_at', models.DateTimeField(blank=True, db_column='promotedAt', null=True)),
                ('promotion_reason', models.TextField(blank=True, db_column='promotionReason', null=True)),
                ('last_calculated', models.DateTimeField(auto_now=True, db_column='lastCalculated')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('clauseId', models.CharField(max_length=36, db_column='clauseId', unique=True)),
            ],
            options={
                'db_table': 'clause_health_metrics',
                'ordering': ['-health_score'],
                'indexes': [models.Index(fields=['-health_score', 'status'], name='clause_heal_healthS_c496a8_idx'), models.Index(fields=['status', '-success_rate'], name='clause_heal_status_67ae43_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClauseEvent',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('EXECUTED', 'Contract Executed'), ('DISPUTED', 'Clause Disputed'), ('RENEWED', 'Contract Renewed'), ('LITIGATED', 'Legal Litigation')], db_column='eventType', max_length=20)),
                ('outcome_score', models.FloatField(db_column='outcomeScore', help_text='Positive outcome = 1.0, Negative outcome = 0.0, Neutral = 0.5')),
                ('description', models.TextField(blank=True, help_text='Details about the event', null=True)),
                ('jurisdiction', models.CharField(blank=True, help_text='Where the event occurred', max_length=100, null=True)),
                ('counterparty_type', models.CharField(blank=True, db_column='counterpartyType', max_length=100, null=True)),
                ('settlement_amount', models.DecimalField(blank=True, db_column='settlementAmount', decimal_places=2, help_text='Settlement cost if disputed/litigated', max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('clauseVersionId', models.CharField(max_length=36, db_column='clauseVersionId')),
                ('contractId', models.CharField(max_length=36, db_column='contractId', blank=True, null=True)),
            ],
            options={
                'db_table': 'clause_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clause_version', '-created_at'], name='clause_even_clauseV_f0800c_idx'), models.Index(fields=['event_type', 'outcome_score'], name='clause_even_eventTy_547db0_idx'), models.Index(fields=['contract', 'event_type'], name='clause_even_contrac_b47ecf_idx')],
            },
        ),
    ]
